In [2]:
# 1. 꼬여있는 패키지들 전부 삭제
%pip uninstall pyannote.audio torch torchaudio torchvision -y

# 2. 윈도우에서 가장 안정적인 조합으로 한 번에 설치
# torch 2.2.2 버전과 torchaudio 2.2.2 버전은 WinError 127 해결에 가장 검증된 조합입니다.
%pip install torch==2.2.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118
%pip install pyannote.audio==3.1.1
%pip install numpy==1.26

Found existing installation: pyannote.audio 3.1.1
Uninstalling pyannote.audio-3.1.1:
  Successfully uninstalled pyannote.audio-3.1.1
Found existing installation: torch 2.2.2
Uninstalling torch-2.2.2:
  Successfully uninstalled torch-2.2.2
Found existing installation: torchaudio 2.11.0
Uninstalling torchaudio-2.11.0:
  Successfully uninstalled torchaudio-2.11.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\Users\lsh8389\AppData\Local\Temp\pip-uninstall-kpihhskw'.
You can safely remove it manually.
WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\torch\~ib'.
You can safely remove it manually.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Skipping torchvision as it is not installed.

Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch==2.2.2
  Downloading torch-2.2.2%2Bcu118-cp312-cp312-win_amd64.whl (2704.2 MB)
     ---------------------------------------- 0.0/2.7 GB ? eta -:--:--
     ---------------------------------------- 0.0/2.7 GB 98.1 MB/s eta 0:00:28
      --------------------------------------- 0.0/2.7 GB 96.9 MB/s eta 0:00:28
      --------------------------------------- 0.1/2.7 GB 98.6 MB/s eta 0:00:27
     - -------------------------------------- 0.1/2.7 GB 99.4 MB/s eta 0:00:27
     - -------------------------------------- 0.1/2.7 GB 102.7 MB/s eta 0:00:26
     - -------------------------------------- 0.1/2.7 GB 101.3 MB/s eta 0:00:26
     -- ------------------------------------- 0.1/2.7 GB 99.2 MB/s eta 0:00:26
     -- ------------------------------------- 0.2/2.7 GB 100.4 MB/s eta 0:00:26
     -- ------------------------------------- 0.2/2.7 GB 100.5 MB/s eta 0:00:26
     --- ------------------------------------ 0.2/2.7 GB 101.1 MB/s eta 0:00:25
     --- ------------------------------------ 0.2/2.7 GB 100.7 MB/s eta 0:00:25
     --- ------------------------------------ 0.2/2.7 GB 100.5 MB/s eta 0:00:25
     ---- ----------------------------------- 0.3/2.7 GB 100.3 MB/s eta 0:00:25
     ---- ----------------------------------- 0.3/2.7 GB 101.6 MB/s eta 0:00:24
     ---- ----------------------------------- 0.3/2.7 GB 101.0 MB/s eta 0:00:24
     ---- ----------------------------------- 0.3/2.7 GB 100.4 MB/s eta 0:00:24
     ----- ---------------------------------- 0.4/2.7 GB 99.8 MB/s eta 0:00:24
     ----- ---------------------------------- 0.4/2.7 GB 99.8 MB/s eta 0:00:24
     ----- ---------------------------------- 0.4/2.7 GB 101.0 MB/s eta 0:00:23
     ------ --------------------------------- 0.4/2.7 GB 101.0 MB/s eta 0:00:23
     ------ --------------------------------- 0.4/2.7 GB 101.0 MB/s eta 0:00:23
     ------ --------------------------------- 0.5/2.7 GB 101.0 MB/s eta 0:00:23
     ------- -------------------------------- 0.5/2.7 GB 101.0 MB/s eta 0:00:22
     ------- -------------------------------- 0.5/2.7 GB 101.6 MB/s eta 0:00:22
     ------- -------------------------------- 0.5/2.7 GB 101.6 MB/s eta 0:00:22
     -------- ------------------------------- 0.5/2.7 GB 101.5 MB/s eta 0:00:22
     -------- ------------------------------- 0.6/2.7 GB 102.2 MB/s eta 0:00:21
     -------- ------------------------------- 0.6/2.7 GB 102.8 MB/s eta 0:00:21
     --------- ------------------------------ 0.6/2.7 GB 103.5 MB/s eta 0:00:21
     --------- ------------------------------ 0.6/2.7 GB 102.8 MB/s eta 0:00:21
     --------- ------------------------------ 0.7/2.7 GB 102.9 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 102.8 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 101.0 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 101.6 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 102.2 MB/s eta 0:00:20
     ----------- ---------------------------- 0.8/2.7 GB 102.2 MB/s eta 0:00:19
     ----------- ---------------------------- 0.8/2.7 GB 102.2 MB/s eta 0:00:19
     ----------- ---------------------------- 0.8/2.7 GB 101.6 MB/s eta 0:00:19
     ------------ --------------------------- 0.8/2.7 GB 101.5 MB/s eta 0:00:19
     ------------ --------------------------- 0.9/2.7 GB 101.0 MB/s eta 0:00:19
     ------------ --------------------------- 0.9/2.7 GB 101.0 MB/s eta 0:00:19
     ------------- -------------------------- 0.9/2.7 GB 101.6 MB/s eta 0:00:18
     ------------- -------------------------- 0.9/2.7 GB 100.4 MB/s eta 0:00:18
     ------------- -------------------------- 0.9/2.7 GB 101.0 MB/s eta 0:00:18
     -------------- ------------------------- 1.0/2.7 GB 103.5 MB/s eta 0:00:17
     -------------- ------------------------- 1.0/2.7 GB 103.4 MB/s eta 0:00:17
     -------------- ------------------------- 1.0/2.7 GB 102.8 MB/s eta 0:00:17
     --------------- ------------------------ 1.0/2.7 GB 102.8 MB/s eta 0:00:17
     --------------- ------------------------ 1.0/2.7 GB 103.5 MB/s eta 0:00:17
     --------------- ------------------------ 1.1/2.7 GB 102.2 MB/s eta 0:00:17
     ---------------- ----------------------- 1.1/2.7 GB 103.5 MB/s eta 0:00:16
     ---------------- ----------------------- 1.1/2.7 GB 103.5 MB/s eta 0:00:16
     ---------------- ----------------------- 1.1/2.7 GB 103.5 MB/s eta 0:00:16
     ----------------- ---------------------- 1.2/2.7 GB 103.4 MB/s eta 0:00:16
     ----------------- ---------------------- 1.2/2.7 GB 103.4 MB/s eta 0:00:15
     ----------------- ---------------------- 1.2/2.7 GB 102.8 MB/s eta 0:00:15
     ----------------- ---------------------- 1.2/2.7 GB 101.6 MB/s eta 0:00:15
     ------------------ --------------------- 1.2/2.7 GB 100.4 MB/s eta 0:00:15
     ------------------ --------------------- 1.2/2.7 GB 97.5 MB/s eta 0:00:15
     ------------------ --------------------- 1.3/2.7 GB 94.7 MB/s eta 0:00:16
     ------------------ --------------------- 1.3/2.7 GB 92.6 MB/s eta 0:00:16
     ------------------ --------------------- 1.3/2.7 GB 88.7 MB/s eta 0:00:17
     ------------------- -------------------- 1.3/2.7 GB 84.6 MB/s eta 0:00:17
     ------------------- -------------------- 1.3/2.7 GB 81.0 MB/s eta 0:00:18
     ------------------- -------------------- 1.3/2.7 GB 75.2 MB/s eta 0:00:19
     ------------------- -------------------- 1.3/2.7 GB 71.9 MB/s eta 0:00:20
     ------------------- -------------------- 1.3/2.7 GB 68.7 MB/s eta 0:00:21
     ------------------- -------------------- 1.3/2.7 GB 65.2 MB/s eta 0:00:22
     ------------------- -------------------- 1.3/2.7 GB 62.3 MB/s eta 0:00:23
     ------------------- -------------------- 1.3/2.7 GB 60.1 MB/s eta 0:00:24
     ------------------- -------------------- 1.3/2.7 GB 57.0 MB/s eta 0:00:25
     ------------------- -------------------- 1.3/2.7 GB 57.0 MB/s eta 0:00:25
     ------------------- -------------------- 1.3/2.7 GB 57.0 MB/s eta 0:00:25
     ------------------- -------------------- 1.3/2.7 GB 57.0 MB/s eta 0:00:25
     ------------------- -------------------- 1.3/2.7 GB 57.0 MB/s eta 0:00:25
     ------------------- -------------------- 1.3/2.7 GB 57.0 MB/s eta 0:00:25
     ------------------- -------------------- 1.3/2.7 GB 57.0 MB/s eta 0:00:25
     ------------------- -------------------- 1.3/2.7 GB 57.0 MB/s eta 0:00:25
     ------------------- -------------------- 1.3/2.7 GB 57.0 MB/s eta 0:00:25
     ------------------- -------------------- 1.3/2.7 GB 57.0 MB/s eta 0:00:25
     ------------------- -------------------- 1.3/2.7 GB 39.8 MB/s eta 0:00:36
     ------------------- -------------------- 1.3/2.7 GB 39.8 MB/s eta 0:00:36
     ------------------- -------------------- 1.3/2.7 GB 39.8 MB/s eta 0:00:36
     ------------------- -------------------- 1.3/2.7 GB 39.8 MB/s eta 0:00:36
     ------------------- -------------------- 1.3/2.7 GB 35.4 MB/s eta 0:00:40
     ------------------- -------------------- 1.3/2.7 GB 35.1 MB/s eta 0:00:40
     ------------------- -------------------- 1.3/2.7 GB 35.1 MB/s eta 0:00:39
     -------------------- ------------------- 1.4/2.7 GB 35.1 MB/s eta 0:00:39
     -------------------- ------------------- 1.4/2.7 GB 35.1 MB/s eta 0:00:38
     -------------------- ------------------- 1.4/2.7 GB 35.1 MB/s eta 0:00:37
     --------------------- ------------------ 1.4/2.7 GB 35.2 MB/s eta 0:00:37
     --------------------- ------------------ 1.5/2.7 GB 35.4 MB/s eta 0:00:36
     --------------------- ------------------ 1.5/2.7 GB 35.5 MB/s eta 0:00:35
     ---------------------- ----------------- 1.5/2.7 GB 35.7 MB/s eta 0:00:34
     ---------------------- ----------------- 1.5/2.7 GB 35.3 MB/s eta 0:00:34
     ---------------------- ----------------- 1.5/2.7 GB 34.5 MB/s eta 0:00:35
     ---------------------- ----------------- 1.5/2.7 GB 33.8 MB/s eta 0:00:36
     ---------------------- ----------------- 1.5/2.7 GB 33.3 MB/s eta 0:00:36
     ---------------------- ----------------- 1.5/2.7 GB 32.9 MB/s eta 0:00:36
     ---------------------- ----------------- 1.5/2.7 GB 32.4 MB/s eta 0:00:37
     ---------------------- ----------------- 1.5/2.7 GB 31.8 MB/s eta 0:00:37
     ---------------------- ----------------- 1.5/2.7 GB 31.4 MB/s eta 0:00:37
     ---------------------- ----------------- 1.5/2.7 GB 31.5 MB/s eta 0:00:37
     ---------------------- ----------------- 1.6/2.7 GB 32.2 MB/s eta 0:00:36
     ----------------------- ---------------- 1.6/2.7 GB 32.9 MB/s eta 0:00:35
     ----------------------- ---------------- 1.6/2.7 GB 33.5 MB/s eta 0:00:35
     ----------------------- ---------------- 1.6/2.7 GB 34.2 MB/s eta 0:00:34
     ----------------------- ---------------- 1.6/2.7 GB 54.2 MB/s eta 0:00:21
     ----------------------- ---------------- 1.6/2.7 GB 53.0 MB/s eta 0:00:22
     ----------------------- ---------------- 1.6/2.7 GB 51.4 MB/s eta 0:00:22
     ----------------------- ---------------- 1.6/2.7 GB 49.9 MB/s eta 0:00:23
     ----------------------- ---------------- 1.6/2.7 GB 48.6 MB/s eta 0:00:23
     ----------------------- ---------------- 1.6/2.7 GB 47.6 MB/s eta 0:00:24
     ----------------------- ---------------- 1.6/2.7 GB 46.3 MB/s eta 0:00:24
     ----------------------- ---------------- 1.6/2.7 GB 45.3 MB/s eta 0:00:24
     ------------------------ --------------- 1.6/2.7 GB 44.3 MB/s eta 0:00:25
     ------------------------ --------------- 1.6/2.7 GB 43.4 MB/s eta 0:00:25
     ------------------------ --------------- 1.6/2.7 GB 42.5 MB/s eta 0:00:26
     ------------------------ --------------- 1.6/2.7 GB 41.5 MB/s eta 0:00:26
     ------------------------ --------------- 1.7/2.7 GB 40.9 MB/s eta 0:00:26
     ------------------------ --------------- 1.7/2.7 GB 40.0 MB/s eta 0:00:27
     ------------------------ --------------- 1.7/2.7 GB 39.2 MB/s eta 0:00:27
     ------------------------ --------------- 1.7/2.7 GB 38.4 MB/s eta 0:00:27
     ------------------------ --------------- 1.7/2.7 GB 37.5 MB/s eta 0:00:28
     ------------------------ --------------- 1.7/2.7 GB 36.8 MB/s eta 0:00:28
     ------------------------- -------------- 1.7/2.7 GB 36.0 MB/s eta 0:00:29
     ------------------------- -------------- 1.7/2.7 GB 35.3 MB/s eta 0:00:29
     ------------------------- -------------- 1.7/2.7 GB 34.5 MB/s eta 0:00:29
     ------------------------- -------------- 1.7/2.7 GB 33.9 MB/s eta 0:00:30
     ------------------------- -------------- 1.7/2.7 GB 33.1 MB/s eta 0:00:30
     ------------------------- -------------- 1.7/2.7 GB 32.4 MB/s eta 0:00:31
     ------------------------- -------------- 1.7/2.7 GB 31.8 MB/s eta 0:00:31
     ------------------------- -------------- 1.7/2.7 GB 31.0 MB/s eta 0:00:32
     ------------------------- -------------- 1.7/2.7 GB 30.6 MB/s eta 0:00:32
     ------------------------- -------------- 1.7/2.7 GB 30.1 MB/s eta 0:00:32
     ------------------------- -------------- 1.8/2.7 GB 29.6 MB/s eta 0:00:33
     ------------------------- -------------- 1.8/2.7 GB 29.0 MB/s eta 0:00:33
     -------------------------- ------------- 1.8/2.7 GB 28.6 MB/s eta 0:00:33
     -------------------------- ------------- 1.8/2.7 GB 29.3 MB/s eta 0:00:32
     -------------------------- ------------- 1.8/2.7 GB 29.7 MB/s eta 0:00:32
     -------------------------- ------------- 1.8/2.7 GB 29.8 MB/s eta 0:00:31
     -------------------------- ------------- 1.8/2.7 GB 30.1 MB/s eta 0:00:31
     -------------------------- ------------- 1.8/2.7 GB 30.4 MB/s eta 0:00:30
     -------------------------- ------------- 1.8/2.7 GB 30.6 MB/s eta 0:00:30
     -------------------------- ------------- 1.8/2.7 GB 31.0 MB/s eta 0:00:29
     -------------------------- ------------- 1.8/2.7 GB 31.6 MB/s eta 0:00:28
     --------------------------- ------------ 1.8/2.7 GB 32.4 MB/s eta 0:00:27
     --------------------------- ------------ 1.8/2.7 GB 32.8 MB/s eta 0:00:27
     --------------------------- ------------ 1.9/2.7 GB 33.2 MB/s eta 0:00:26
     --------------------------- ------------ 1.9/2.7 GB 33.5 MB/s eta 0:00:26
     --------------------------- ------------ 1.9/2.7 GB 33.7 MB/s eta 0:00:25
     --------------------------- ------------ 1.9/2.7 GB 33.7 MB/s eta 0:00:25
     --------------------------- ------------ 1.9/2.7 GB 33.7 MB/s eta 0:00:25
     ---------------------------- ----------- 1.9/2.7 GB 33.9 MB/s eta 0:00:24
     ---------------------------- ----------- 1.9/2.7 GB 33.8 MB/s eta 0:00:24
     ---------------------------- ----------- 1.9/2.7 GB 33.5 MB/s eta 0:00:24
     ---------------------------- ----------- 1.9/2.7 GB 33.0 MB/s eta 0:00:25
     ---------------------------- ----------- 1.9/2.7 GB 32.7 MB/s eta 0:00:25
     ---------------------------- ----------- 1.9/2.7 GB 32.9 MB/s eta 0:00:24
     ---------------------------- ----------- 1.9/2.7 GB 32.9 MB/s eta 0:00:24
     ---------------------------- ----------- 1.9/2.7 GB 33.2 MB/s eta 0:00:24
     ---------------------------- ----------- 1.9/2.7 GB 33.4 MB/s eta 0:00:23
     ---------------------------- ----------- 2.0/2.7 GB 33.9 MB/s eta 0:00:23
     ----------------------------- ---------- 2.0/2.7 GB 34.1 MB/s eta 0:00:22
     ----------------------------- ---------- 2.0/2.7 GB 34.4 MB/s eta 0:00:22
     ----------------------------- ---------- 2.0/2.7 GB 35.5 MB/s eta 0:00:21
     ----------------------------- ---------- 2.0/2.7 GB 36.0 MB/s eta 0:00:20
     ----------------------------- ---------- 2.0/2.7 GB 36.2 MB/s eta 0:00:20
     ----------------------------- ---------- 2.0/2.7 GB 36.4 MB/s eta 0:00:20
     ----------------------------- ---------- 2.0/2.7 GB 36.7 MB/s eta 0:00:19
     ----------------------------- ---------- 2.0/2.7 GB 37.8 MB/s eta 0:00:19
     ----------------------------- ---------- 2.0/2.7 GB 37.8 MB/s eta 0:00:18
     ------------------------------ --------- 2.0/2.7 GB 37.0 MB/s eta 0:00:19
     ------------------------------ --------- 2.0/2.7 GB 36.9 MB/s eta 0:00:19
     ------------------------------ --------- 2.0/2.7 GB 36.6 MB/s eta 0:00:19
     ------------------------------ --------- 2.0/2.7 GB 35.9 MB/s eta 0:00:19
     ------------------------------ --------- 2.1/2.7 GB 35.7 MB/s eta 0:00:19
     ------------------------------ --------- 2.1/2.7 GB 35.7 MB/s eta 0:00:18
     ------------------------------ --------- 2.1/2.7 GB 35.3 MB/s eta 0:00:19
     ------------------------------ --------- 2.1/2.7 GB 35.2 MB/s eta 0:00:18
     ------------------------------ --------- 2.1/2.7 GB 34.9 MB/s eta 0:00:18
     ------------------------------ --------- 2.1/2.7 GB 34.8 MB/s eta 0:00:18
     ------------------------------ --------- 2.1/2.7 GB 34.5 MB/s eta 0:00:18
     ------------------------------- -------- 2.1/2.7 GB 34.3 MB/s eta 0:00:18
     ------------------------------- -------- 2.1/2.7 GB 34.3 MB/s eta 0:00:18
     ------------------------------- -------- 2.1/2.7 GB 34.2 MB/s eta 0:00:18
     ------------------------------- -------- 2.1/2.7 GB 34.1 MB/s eta 0:00:18
     ------------------------------- -------- 2.1/2.7 GB 33.9 MB/s eta 0:00:17
     ------------------------------- -------- 2.1/2.7 GB 33.7 MB/s eta 0:00:17
     ------------------------------- -------- 2.1/2.7 GB 33.1 MB/s eta 0:00:17
     ------------------------------- -------- 2.1/2.7 GB 32.9 MB/s eta 0:00:17
     ------------------------------- -------- 2.2/2.7 GB 32.7 MB/s eta 0:00:17
     ------------------------------- -------- 2.2/2.7 GB 32.3 MB/s eta 0:00:17
     -------------------------------- ------- 2.2/2.7 GB 32.5 MB/s eta 0:00:17
     -------------------------------- ------- 2.2/2.7 GB 32.4 MB/s eta 0:00:17
     -------------------------------- ------- 2.2/2.7 GB 32.3 MB/s eta 0:00:17
     -------------------------------- ------- 2.2/2.7 GB 32.1 MB/s eta 0:00:17
     -------------------------------- ------- 2.2/2.7 GB 32.1 MB/s eta 0:00:17
     -------------------------------- ------- 2.2/2.7 GB 32.1 MB/s eta 0:00:17
     -------------------------------- ------- 2.2/2.7 GB 30.2 MB/s eta 0:00:18
     -------------------------------- ------- 2.2/2.7 GB 30.2 MB/s eta 0:00:18
     -------------------------------- ------- 2.2/2.7 GB 28.7 MB/s eta 0:00:19
     -------------------------------- ------- 2.2/2.7 GB 28.7 MB/s eta 0:00:19
     -------------------------------- ------- 2.2/2.7 GB 28.7 MB/s eta 0:00:19
     -------------------------------- ------- 2.2/2.7 GB 26.9 MB/s eta 0:00:20
     -------------------------------- ------- 2.2/2.7 GB 26.6 MB/s eta 0:00:20
     -------------------------------- ------- 2.2/2.7 GB 26.6 MB/s eta 0:00:20
     -------------------------------- ------- 2.2/2.7 GB 26.6 MB/s eta 0:00:20
     -------------------------------- ------- 2.2/2.7 GB 25.5 MB/s eta 0:00:21
     -------------------------------- ------- 2.2/2.7 GB 25.3 MB/s eta 0:00:20
     -------------------------------- ------- 2.2/2.7 GB 26.0 MB/s eta 0:00:19
     --------------------------------- ------ 2.2/2.7 GB 26.9 MB/s eta 0:00:18
     --------------------------------- ------ 2.3/2.7 GB 28.2 MB/s eta 0:00:16
     --------------------------------- ------ 2.3/2.7 GB 28.6 MB/s eta 0:00:15
     --------------------------------- ------ 2.3/2.7 GB 28.5 MB/s eta 0:00:15
     --------------------------------- ------ 2.3/2.7 GB 28.2 MB/s eta 0:00:15
     --------------------------------- ------ 2.3/2.7 GB 28.1 MB/s eta 0:00:15
     ---------------------------------- ----- 2.3/2.7 GB 28.4 MB/s eta 0:00:15
     ---------------------------------- ----- 2.3/2.7 GB 28.8 MB/s eta 0:00:14
     ---------------------------------- ----- 2.3/2.7 GB 28.8 MB/s eta 0:00:14
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: Exception:
Traceback (most recent call last):
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 897, in _error_catcher
    yield
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 1022, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 1005, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 104, in read
    self.__buf.write(data)
  File "C:\Users\lsh8389\AppData\Local\Programs\Python\Python312\Lib\tempfile.py", line 499, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 109, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 102, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\cli\req_command.py", line 101, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\commands\install.py", line 479, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 99, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 601, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 434, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 150, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 194, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 165, in __bool__
    self._bool = any(self)
                 ^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 149, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 39, in _iter_built
    candidate = func()
                ^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 182, in _make_candidate_from_link
    base: BaseCandidate | None = self._make_base_candidate_from_link(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 326, in __init__
    super().__init__(
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 168, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 246, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 337, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 542, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 613, in _prepare_linked_requirement
    local_file = unpack_url(
                 ^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 180, in unpack_url
    file = get_http_url(
           ^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 121, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\network\download.py", line 193, in __call__
    self._process_response(download, resp)
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\network\download.py", line 210, in _process_response
    for chunk in chunks:
                 ^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 69, in _rich_download_progress_bar
    for chunk in iterable:
                 ^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\network\utils.py", line 65, in response_chunks
    for chunk in response.raw.stream(
                 ^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 1251, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 1106, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 1021, in _raw_read
    with self._error_catcher():
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lsh8389\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 924, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: OSError(28, 'No space left on device')", OSError(28, 'No space left on device'))

Collecting pyannote.audio==3.1.1
  Using cached pyannote.audio-3.1.1-py2.py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: asteroid-filterbanks>=0.4 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.4.0)
Requirement already satisfied: einops>=0.6.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.12.0)
Requirement already satisfied: lightning>=2.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: omegaconf<3.0,>=2.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.3.0)
Requirement already satisfied: pyannote.core>=5.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.0.1)
Requirement already satisfied: pyannote.database>=5.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.1.1)
Requirement already satisfied: pyannote.metrics>=3.2 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pyannote.pipeline>=3.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pytorch-metric-learning>=2.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.9.0)
Requirement already satisfied: rich>=12.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (15.0.0)
Requirement already satisfied: semver>=3.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (3.0.4)
Requirement already satisfied: soundfile>=0.12.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.13.1)
Requirement already satisfied: speechbrain>=0.5.14 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.1.0)
Requirement already satisfied: tensorboardX>=2.6 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.5)
Collecting torch>=2.0.0 (from pyannote.audio==3.1.1)
  Using cached torch-2.11.0-cp312-cp312-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: torch-audiomentations>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.12.0)
Collecting torchaudio>=2.0.0 (from pyannote.audio==3.1.1)
  Using cached torchaudio-2.11.0-cp312-cp312-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: torchmetrics>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.9.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (6.0.3)
Requirement already satisfied: numpy in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (2.4.4)
Requirement already satisfied: typing-extensions in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (4.15.0)
Requirement already satisfied: filelock>=3.10.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (26.2)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (4.67.3)
Requirement already satisfied: typer in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.25.0)
Requirement already satisfied: anyio in c:\LLM\ch03_venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (4.13.0)
Requirement already satisfied: certifi in c:\LLM\ch03_venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\LLM\ch03_venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (1.0.9)
Requirement already satisfied: idna in c:\LLM\ch03_venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.13)
Requirement already satisfied: h11>=0.16 in c:\LLM\ch03_venv\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.16.0)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (0.15.3)
Requirement already satisfied: pytorch-lightning in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\LLM\ch03_venv\Lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13.5)
Requirement already satisfied: setuptools<82 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.1.6)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.23.0)
Requirement already satisfied: pandas>=2.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (3.0.2)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2026.2)
Requirement already satisfied: scikit-learn>=1.6.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: scipy>=1.15.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.17.1)
Requirement already satisfied: optuna>=4.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.18.4)
Requirement already satisfied: colorlog in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (2.0.49)
Requirement already satisfied: Mako in c:\LLM\ch03_venv\Lib\site-packages (from alembic>=1.5.0->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.3.12)
Requirement already satisfied: six>=1.5 in c:\LLM\ch03_venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\LLM\ch03_venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->pyannote.audio==3.1.1) (0.1.2)
Requirement already satisfied: joblib>=1.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (3.6.0)
Requirement already satisfied: cffi>=1.0 in c:\LLM\ch03_venv\Lib\site-packages (from soundfile>=0.12.1->pyannote.audio==3.1.1) (2.0.0)
Requirement already satisfied: pycparser in c:\LLM\ch03_venv\Lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->pyannote.audio==3.1.1) (3.0)
Requirement already satisfied: hyperpyyaml>=0.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (1.2.3)
Requirement already satisfied: requests>=2.20.0 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (2.33.1)
Requirement already satisfied: sentencepiece>=0.1.91 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.1)
Requirement already satisfied: ruamel.yaml<0.19.0,>=0.17.28 in c:\LLM\ch03_venv\Lib\site-packages (from hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.18.17)
Requirement already satisfied: ruamel.yaml.clib>=0.2.15 in c:\LLM\ch03_venv\Lib\site-packages (from ruamel.yaml<0.19.0,>=0.17.28->hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.15)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests>=2.20.0->speechbrain>=0.5.14->pyannote.audio==3.1.1) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests>=2.20.0->speechbrain>=0.5.14->pyannote.audio==3.1.1) (2.6.3)
Requirement already satisfied: greenlet>=1 in c:\LLM\ch03_venv\Lib\site-packages (from sqlalchemy>=1.4.2->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->pyannote.audio==3.1.1) (1.3.0)
Requirement already satisfied: protobuf>=3.20 in c:\LLM\ch03_venv\Lib\site-packages (from tensorboardX>=2.6->pyannote.audio==3.1.1) (6.33.6)
Requirement already satisfied: julius<0.3,>=0.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (0.2.7)
Requirement already satisfied: torch-pitch-shift>=1.2.2 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.2.5)
Requirement already satisfied: primePy>=1.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-pitch-shift>=1.2.2->torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch>=2.0.0->pyannote.audio==3.1.1) (3.0.3)
Requirement already satisfied: click>=8.2.1 in c:\LLM\ch03_venv\Lib\site-packages (from typer->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from typer->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\LLM\ch03_venv\Lib\site-packages (from typer->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.0.4)
Using cached pyannote.audio-3.1.1-py2.py3-none-any.whl (208 kB)
Using cached torch-2.11.0-cp312-cp312-win_amd64.whl (114.6 MB)
Using cached torchaudio-2.11.0-cp312-cp312-win_amd64.whl (328 kB)
Installing collected packages: torchaudio, torch, pyannote.audio

   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ---------------------------------------- 0/3 [torchaudio]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Collecting numpy==1.26
  Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl (15.5 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.4
    Uninstalling numpy-2.4.4:
      Successfully uninstalled numpy-2.4.4
Successfully installed numpy-1.26.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
  WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~~mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~~mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyannote-core 6.0.1 requires numpy>=2.0, but you have numpy 1.26.0 which is incompatible.
pyannote-metrics 4.0.0 requires numpy>=2.2.2, but you have numpy 1.26.0 which is incompatible.
scipy 1.17.1 requires numpy<2.7,>=1.26.4, but you have numpy 1.26.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

In [1]:
from pyannote.audio import Pipeline
import torch

# 1. 모델 불러오기
pipeline = Pipeline.from_pretrained(
    "pyannote/speaker-diarization-3.1",
    use_auth_token="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"
)

# 2. 장치 설정 (에러 방지를 위해 이번에는 강제로 CPU로 먼저 테스트해봅니다)
pipeline.to(torch.device("cpu"))
print("✅ 라이브러리 로드 성공! CPU 모드로 시작합니다.")

# 3. 화자 분리 실행
# 파일이 audio/ 폴더 안에 있는지 다시 한번 확인해주세요!
diarization = pipeline("audio/lsy_audio_2023_58s.mp3")

# 4. 결과 저장
with open("audio/result.rttm", "w", encoding='utf-8') as rttm:
    diarization.write_rttm(rttm)

print("✨ 드디어 화자 분리가 성공적으로 완료되었습니다!")

c:\LLM\ch03_venv\Lib\site-packages\torchmetrics\__init__.py:31: UserWarning: A NumPy version >=1.26.4 and <2.7.0 is required for this version of SciPy (detected version 1.26.0)
  import scipy.signal
c:\LLM\ch03_venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

AttributeError: module 'torchaudio' has no attribute 'set_audio_backend'

In [2]:
# 1. 꼬여있는 패키지 확실히 삭제
%pip uninstall pyannote.audio torchaudio torch -y

# 2. 윈도우에서 가장 안정적인 구버전 조합으로 재설치
# torchaudio 2.2.2는 해당 에러가 발생하지 않는 마지막 안정 버전입니다.
%pip install torch==2.2.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118
%pip install pyannote.audio==3.1.1
%pip install numpy==1.26

Found existing installation: pyannote.audio 3.1.1
Uninstalling pyannote.audio-3.1.1:
  Successfully uninstalled pyannote.audio-3.1.1
Found existing installation: torchaudio 2.11.0
Uninstalling torchaudio-2.11.0:
  Successfully uninstalled torchaudio-2.11.0
Found existing installation: torch 2.11.0
Uninstalling torch-2.11.0:
  Successfully uninstalled torch-2.11.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~-rchaudio'.
You can safely remove it manually.
WARNING: Failed to remove contents in a temporary directory 'C:\Users\lsh8389\AppData\Local\Temp\pip-uninstall-ekpr8p8y'.
You can safely remove it manually.
WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\torch\~-b'.
You can safely remove it manually.

Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch==2.2.2
  Downloading torch-2.2.2%2Bcu118-cp312-cp312-win_amd64.whl (2704.2 MB)
     ---------------------------------------- 0.0/2.7 GB ? eta -:--:--
     ---------------------------------------- 0.0/2.7 GB 102.0 MB/s eta 0:00:27
      --------------------------------------- 0.0/2.7 GB 100.6 MB/s eta 0:00:27
      --------------------------------------- 0.1/2.7 GB 101.1 MB/s eta 0:00:27
     - -------------------------------------- 0.1/2.7 GB 99.7 MB/s eta 0:00:27
     - -------------------------------------- 0.1/2.7 GB 100.4 MB/s eta 0:00:26
     - -------------------------------------- 0.1/2.7 GB 101.7 MB/s eta 0:00:26
     -- ------------------------------------- 0.2/2.7 GB 102.8 MB/s eta 0:00:25
     -- ------------------------------------- 0.2/2.7 GB 103.1 MB/s eta 0:00:25
     -- ------------------------------------- 0.2/2.7 GB 101.2 MB/s eta 0:00:25
     --- ------------------------------------ 0.2/2.7 GB 100.8 MB/s eta 0:00:25
     --- ------------------------------------ 0.2/2.7 GB 100.4 MB/s eta 0:00:25
     --- ------------------------------------ 0.3/2.7 GB 101.6 MB/s eta 0:00:25
     ---- ----------------------------------- 0.3/2.7 GB 101.0 MB/s eta 0:00:25
     ---- ----------------------------------- 0.3/2.7 GB 103.5 MB/s eta 0:00:24
     ---- ----------------------------------- 0.3/2.7 GB 102.2 MB/s eta 0:00:24
     ----- ---------------------------------- 0.3/2.7 GB 102.2 MB/s eta 0:00:24
     ----- ---------------------------------- 0.4/2.7 GB 102.8 MB/s eta 0:00:23
     ----- ---------------------------------- 0.4/2.7 GB 103.5 MB/s eta 0:00:23
     ------ --------------------------------- 0.4/2.7 GB 102.9 MB/s eta 0:00:23
     ------ --------------------------------- 0.4/2.7 GB 104.8 MB/s eta 0:00:22
     ------ --------------------------------- 0.5/2.7 GB 105.4 MB/s eta 0:00:22
     ------- -------------------------------- 0.5/2.7 GB 106.8 MB/s eta 0:00:21
     ------- -------------------------------- 0.5/2.7 GB 106.7 MB/s eta 0:00:21
     ------- -------------------------------- 0.5/2.7 GB 106.8 MB/s eta 0:00:21
     -------- ------------------------------- 0.5/2.7 GB 106.1 MB/s eta 0:00:21
     -------- ------------------------------- 0.6/2.7 GB 104.8 MB/s eta 0:00:21
     -------- ------------------------------- 0.6/2.7 GB 104.8 MB/s eta 0:00:21
     --------- ------------------------------ 0.6/2.7 GB 105.4 MB/s eta 0:00:20
     --------- ------------------------------ 0.6/2.7 GB 104.1 MB/s eta 0:00:20
     --------- ------------------------------ 0.7/2.7 GB 104.1 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 104.8 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 103.4 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 102.8 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 103.5 MB/s eta 0:00:20
     ----------- ---------------------------- 0.8/2.7 GB 102.2 MB/s eta 0:00:20
     ----------- ---------------------------- 0.8/2.7 GB 102.2 MB/s eta 0:00:19
     ----------- ---------------------------- 0.8/2.7 GB 101.0 MB/s eta 0:00:19
     ------------ --------------------------- 0.8/2.7 GB 101.6 MB/s eta 0:00:19
     ------------ --------------------------- 0.8/2.7 GB 102.8 MB/s eta 0:00:19
     ------------ --------------------------- 0.9/2.7 GB 101.6 MB/s eta 0:00:19
     ------------- -------------------------- 0.9/2.7 GB 102.2 MB/s eta 0:00:18
     ------------- -------------------------- 0.9/2.7 GB 101.6 MB/s eta 0:00:18
     ------------- -------------------------- 0.9/2.7 GB 99.8 MB/s eta 0:00:18
     ------------- -------------------------- 0.9/2.7 GB 96.4 MB/s eta 0:00:19
     -------------- ------------------------- 1.0/2.7 GB 92.6 MB/s eta 0:00:19
     -------------- ------------------------- 1.0/2.7 GB 90.1 MB/s eta 0:00:20
     -------------- ------------------------- 1.0/2.7 GB 86.8 MB/s eta 0:00:20
     -------------- ------------------------- 1.0/2.7 GB 83.4 MB/s eta 0:00:21
     -------------- ------------------------- 1.0/2.7 GB 79.8 MB/s eta 0:00:22
     -------------- ------------------------- 1.0/2.7 GB 76.9 MB/s eta 0:00:23
     -------------- ------------------------- 1.0/2.7 GB 74.5 MB/s eta 0:00:23
     --------------- ------------------------ 1.0/2.7 GB 72.2 MB/s eta 0:00:24
     --------------- ------------------------ 1.0/2.7 GB 69.8 MB/s eta 0:00:24
     --------------- ------------------------ 1.0/2.7 GB 67.6 MB/s eta 0:00:25
     --------------- ------------------------ 1.0/2.7 GB 65.2 MB/s eta 0:00:26
     --------------- ------------------------ 1.1/2.7 GB 63.2 MB/s eta 0:00:27
     --------------- ------------------------ 1.1/2.7 GB 61.6 MB/s eta 0:00:27
     --------------- ------------------------ 1.1/2.7 GB 60.1 MB/s eta 0:00:28
     ---------------- ----------------------- 1.1/2.7 GB 58.6 MB/s eta 0:00:28
     ---------------- ----------------------- 1.1/2.7 GB 57.0 MB/s eta 0:00:29
     ---------------- ----------------------- 1.1/2.7 GB 55.9 MB/s eta 0:00:29
     ---------------- ----------------------- 1.1/2.7 GB 54.8 MB/s eta 0:00:29
     ---------------- ----------------------- 1.1/2.7 GB 53.9 MB/s eta 0:00:30
     ---------------- ----------------------- 1.1/2.7 GB 52.2 MB/s eta 0:00:30
     ---------------- ----------------------- 1.1/2.7 GB 50.8 MB/s eta 0:00:31
     ----------------- ---------------------- 1.2/2.7 GB 49.6 MB/s eta 0:00:32
     ----------------- ---------------------- 1.2/2.7 GB 48.6 MB/s eta 0:00:32
     ----------------- ---------------------- 1.2/2.7 GB 47.2 MB/s eta 0:00:33
     ----------------- ---------------------- 1.2/2.7 GB 46.2 MB/s eta 0:00:34
     ----------------- ---------------------- 1.2/2.7 GB 45.1 MB/s eta 0:00:34
     ----------------- ---------------------- 1.2/2.7 GB 44.8 MB/s eta 0:00:34
     ----------------- ---------------------- 1.2/2.7 GB 44.3 MB/s eta 0:00:34
     ----------------- ---------------------- 1.2/2.7 GB 43.9 MB/s eta 0:00:34
     ------------------ --------------------- 1.2/2.7 GB 43.3 MB/s eta 0:00:35
     ------------------ --------------------- 1.2/2.7 GB 42.9 MB/s eta 0:00:35
     ------------------ --------------------- 1.2/2.7 GB 42.2 MB/s eta 0:00:35
     ------------------ --------------------- 1.2/2.7 GB 42.1 MB/s eta 0:00:35
     ------------------ --------------------- 1.3/2.7 GB 41.7 MB/s eta 0:00:35
     ------------------ --------------------- 1.3/2.7 GB 41.7 MB/s eta 0:00:35
     ------------------ --------------------- 1.3/2.7 GB 41.3 MB/s eta 0:00:35
     ------------------ --------------------- 1.3/2.7 GB 41.2 MB/s eta 0:00:35
     ------------------- -------------------- 1.3/2.7 GB 41.1 MB/s eta 0:00:35
     ------------------- -------------------- 1.3/2.7 GB 41.4 MB/s eta 0:00:35
     ------------------- -------------------- 1.3/2.7 GB 41.6 MB/s eta 0:00:34
     ------------------- -------------------- 1.3/2.7 GB 41.8 MB/s eta 0:00:34
     ------------------- -------------------- 1.3/2.7 GB 41.7 MB/s eta 0:00:34
     ------------------- -------------------- 1.3/2.7 GB 41.7 MB/s eta 0:00:33
     ------------------- -------------------- 1.3/2.7 GB 41.4 MB/s eta 0:00:33
     ------------------- -------------------- 1.4/2.7 GB 41.3 MB/s eta 0:00:33
     -------------------- ------------------- 1.4/2.7 GB 41.3 MB/s eta 0:00:33
     -------------------- ------------------- 1.4/2.7 GB 41.2 MB/s eta 0:00:33
     -------------------- ------------------- 1.4/2.7 GB 41.3 MB/s eta 0:00:32
     -------------------- ------------------- 1.4/2.7 GB 41.2 MB/s eta 0:00:32
     -------------------- ------------------- 1.4/2.7 GB 41.3 MB/s eta 0:00:32
     -------------------- ------------------- 1.4/2.7 GB 41.7 MB/s eta 0:00:31
     --------------------- ------------------ 1.4/2.7 GB 41.8 MB/s eta 0:00:31
     --------------------- ------------------ 1.4/2.7 GB 41.9 MB/s eta 0:00:31
     --------------------- ------------------ 1.4/2.7 GB 42.1 MB/s eta 0:00:30
     --------------------- ------------------ 1.5/2.7 GB 42.6 MB/s eta 0:00:30
     --------------------- ------------------ 1.5/2.7 GB 44.1 MB/s eta 0:00:29
     --------------------- ------------------ 1.5/2.7 GB 43.6 MB/s eta 0:00:29
     --------------------- ------------------ 1.5/2.7 GB 43.4 MB/s eta 0:00:29
     ---------------------- ----------------- 1.5/2.7 GB 43.6 MB/s eta 0:00:28
     ---------------------- ----------------- 1.5/2.7 GB 44.3 MB/s eta 0:00:28
     ---------------------- ----------------- 1.5/2.7 GB 44.7 MB/s eta 0:00:27
     ---------------------- ----------------- 1.5/2.7 GB 45.4 MB/s eta 0:00:27
     ---------------------- ----------------- 1.5/2.7 GB 45.8 MB/s eta 0:00:26
     ---------------------- ----------------- 1.5/2.7 GB 46.2 MB/s eta 0:00:26
     ---------------------- ----------------- 1.6/2.7 GB 46.6 MB/s eta 0:00:25
     ----------------------- ---------------- 1.6/2.7 GB 46.4 MB/s eta 0:00:25
     ----------------------- ---------------- 1.6/2.7 GB 46.4 MB/s eta 0:00:25
     ----------------------- ---------------- 1.6/2.7 GB 46.2 MB/s eta 0:00:25
     ----------------------- ---------------- 1.6/2.7 GB 45.9 MB/s eta 0:00:25
     ----------------------- ---------------- 1.6/2.7 GB 45.7 MB/s eta 0:00:25
     ----------------------- ---------------- 1.6/2.7 GB 45.1 MB/s eta 0:00:25
     ----------------------- ---------------- 1.6/2.7 GB 45.1 MB/s eta 0:00:25
     ----------------------- ---------------- 1.6/2.7 GB 44.6 MB/s eta 0:00:25
     ------------------------ --------------- 1.6/2.7 GB 44.6 MB/s eta 0:00:25
     ------------------------ --------------- 1.6/2.7 GB 44.2 MB/s eta 0:00:25
     ------------------------ --------------- 1.6/2.7 GB 44.0 MB/s eta 0:00:25
     ------------------------ --------------- 1.7/2.7 GB 44.1 MB/s eta 0:00:24
     ------------------------ --------------- 1.7/2.7 GB 44.0 MB/s eta 0:00:24
     ------------------------ --------------- 1.7/2.7 GB 43.9 MB/s eta 0:00:24
     ------------------------ --------------- 1.7/2.7 GB 44.0 MB/s eta 0:00:24
     ------------------------ --------------- 1.7/2.7 GB 43.5 MB/s eta 0:00:24
     ------------------------- -------------- 1.7/2.7 GB 43.5 MB/s eta 0:00:24
     ------------------------- -------------- 1.7/2.7 GB 43.0 MB/s eta 0:00:24
     ------------------------- -------------- 1.7/2.7 GB 42.6 MB/s eta 0:00:24
     ------------------------- -------------- 1.7/2.7 GB 42.0 MB/s eta 0:00:24
     ------------------------- -------------- 1.7/2.7 GB 41.4 MB/s eta 0:00:24
     ------------------------- -------------- 1.7/2.7 GB 42.3 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 41.9 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 42.8 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 42.6 MB/s eta 0:00:22
     -------------------------- ------------- 1.8/2.7 GB 42.5 MB/s eta 0:00:22
     -------------------------- ------------- 1.8/2.7 GB 42.5 MB/s eta 0:00:22
     -------------------------- ------------- 1.8/2.7 GB 42.3 MB/s eta 0:00:22
     -------------------------- ------------- 1.8/2.7 GB 42.2 MB/s eta 0:00:22
     -------------------------- ------------- 1.8/2.7 GB 42.0 MB/s eta 0:00:22
     --------------------------- ------------ 1.8/2.7 GB 42.0 MB/s eta 0:00:21
     --------------------------- ------------ 1.8/2.7 GB 42.0 MB/s eta 0:00:21
     --------------------------- ------------ 1.8/2.7 GB 42.3 MB/s eta 0:00:21
     --------------------------- ------------ 1.9/2.7 GB 42.4 MB/s eta 0:00:21
     --------------------------- ------------ 1.9/2.7 GB 42.9 MB/s eta 0:00:20
     --------------------------- ------------ 1.9/2.7 GB 42.9 MB/s eta 0:00:20
     --------------------------- ------------ 1.9/2.7 GB 43.0 MB/s eta 0:00:20
     --------------------------- ------------ 1.9/2.7 GB 43.0 MB/s eta 0:00:20
     ---------------------------- ----------- 1.9/2.7 GB 43.0 MB/s eta 0:00:19
     ---------------------------- ----------- 1.9/2.7 GB 42.6 MB/s eta 0:00:19
     ---------------------------- ----------- 1.9/2.7 GB 41.7 MB/s eta 0:00:20
     ---------------------------- ----------- 1.9/2.7 GB 41.7 MB/s eta 0:00:20
     ---------------------------- ----------- 1.9/2.7 GB 41.7 MB/s eta 0:00:20
     ---------------------------- ----------- 1.9/2.7 GB 38.6 MB/s eta 0:00:21
     ---------------------------- ----------- 1.9/2.7 GB 38.6 MB/s eta 0:00:21
     ---------------------------- ----------- 1.9/2.7 GB 38.6 MB/s eta 0:00:21
     ---------------------------- ----------- 1.9/2.7 GB 35.6 MB/s eta 0:00:23
     ---------------------------- ----------- 1.9/2.7 GB 35.6 MB/s eta 0:00:23
     ---------------------------- ----------- 1.9/2.7 GB 35.6 MB/s eta 0:00:23
     ---------------------------- ----------- 1.9/2.7 GB 35.6 MB/s eta 0:00:23
     ---------------------------- ----------- 1.9/2.7 GB 35.6 MB/s eta 0:00:23
     ---------------------------- ----------- 1.9/2.7 GB 35.6 MB/s eta 0:00:23
     ---------------------------- ----------- 1.9/2.7 GB 35.6 MB/s eta 0:00:23
     ---------------------------- ----------- 1.9/2.7 GB 35.6 MB/s eta 0:00:23
     ---------------------------- ----------- 1.9/2.7 GB 35.6 MB/s eta 0:00:23
     ---------------------------- ----------- 1.9/2.7 GB 28.5 MB/s eta 0:00:28
     ---------------------------- ----------- 1.9/2.7 GB 28.5 MB/s eta 0:00:28
     ---------------------------- ----------- 1.9/2.7 GB 28.5 MB/s eta 0:00:28
     ---------------------------- ----------- 1.9/2.7 GB 26.6 MB/s eta 0:00:30
     ---------------------------- ----------- 1.9/2.7 GB 26.6 MB/s eta 0:00:30
     ---------------------------- ----------- 1.9/2.7 GB 26.5 MB/s eta 0:00:30
     ---------------------------- ----------- 2.0/2.7 GB 27.0 MB/s eta 0:00:28
     ----------------------------- ---------- 2.0/2.7 GB 28.0 MB/s eta 0:00:27
     ----------------------------- ---------- 2.0/2.7 GB 28.9 MB/s eta 0:00:25
     ----------------------------- ---------- 2.0/2.7 GB 29.9 MB/s eta 0:00:24
     ------------------------------ --------- 2.0/2.7 GB 30.5 MB/s eta 0:00:23
     ------------------------------ --------- 2.1/2.7 GB 31.4 MB/s eta 0:00:21
     ------------------------------ --------- 2.1/2.7 GB 31.5 MB/s eta 0:00:21
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

Collecting pyannote.audio==3.1.1
  Using cached pyannote.audio-3.1.1-py2.py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: asteroid-filterbanks>=0.4 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.4.0)
Requirement already satisfied: einops>=0.6.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.12.0)
Requirement already satisfied: lightning>=2.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: omegaconf<3.0,>=2.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.3.0)
Requirement already satisfied: pyannote.core>=5.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.0.1)
Requirement already satisfied: pyannote.database>=5.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.1.1)
Requirement already satisfied: pyannote.metrics>=3.2 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pyannote.pipeline>=3.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pytorch-metric-learning>=2.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.9.0)
Requirement already satisfied: rich>=12.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (15.0.0)
Requirement already satisfied: semver>=3.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (3.0.4)
Requirement already satisfied: soundfile>=0.12.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.13.1)
Requirement already satisfied: speechbrain>=0.5.14 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.1.0)
Requirement already satisfied: tensorboardX>=2.6 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.5)
Collecting torch>=2.0.0 (from pyannote.audio==3.1.1)
  Using cached torch-2.11.0-cp312-cp312-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: torch-audiomentations>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.12.0)
Collecting torchaudio>=2.0.0 (from pyannote.audio==3.1.1)
  Using cached torchaudio-2.11.0-cp312-cp312-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: torchmetrics>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.9.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (6.0.3)
Requirement already satisfied: numpy in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (1.26.0)
Requirement already satisfied: typing-extensions in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (4.15.0)
Requirement already satisfied: filelock>=3.10.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.28.1)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (26.2)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (4.67.3)
Requirement already satisfied: typer in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.25.0)
Requirement already satisfied: anyio in c:\LLM\ch03_venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (4.13.0)
Requirement already satisfied: certifi in c:\LLM\ch03_venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\LLM\ch03_venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (1.0.9)
Requirement already satisfied: idna in c:\LLM\ch03_venv\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.13)
Requirement already satisfied: h11>=0.16 in c:\LLM\ch03_venv\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.16.0)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (0.15.3)
Requirement already satisfied: pytorch-lightning in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\LLM\ch03_venv\Lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13.5)
Requirement already satisfied: setuptools<82 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.1.6)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.23.0)
Collecting numpy (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1)
  Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: pandas>=2.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (3.0.2)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2026.2)
Requirement already satisfied: scikit-learn>=1.6.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: scipy>=1.15.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.17.1)
Requirement already satisfied: optuna>=4.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.18.4)
Requirement already satisfied: colorlog in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (2.0.49)
Requirement already satisfied: Mako in c:\LLM\ch03_venv\Lib\site-packages (from alembic>=1.5.0->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.3.12)
Requirement already satisfied: six>=1.5 in c:\LLM\ch03_venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\LLM\ch03_venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->pyannote.audio==3.1.1) (0.1.2)
Requirement already satisfied: joblib>=1.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (3.6.0)
Requirement already satisfied: cffi>=1.0 in c:\LLM\ch03_venv\Lib\site-packages (from soundfile>=0.12.1->pyannote.audio==3.1.1) (2.0.0)
Requirement already satisfied: pycparser in c:\LLM\ch03_venv\Lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->pyannote.audio==3.1.1) (3.0)
Requirement already satisfied: hyperpyyaml>=0.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (1.2.3)
Requirement already satisfied: requests>=2.20.0 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (2.33.1)
Requirement already satisfied: sentencepiece>=0.1.91 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.1)
Requirement already satisfied: ruamel.yaml<0.19.0,>=0.17.28 in c:\LLM\ch03_venv\Lib\site-packages (from hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.18.17)
Requirement already satisfied: ruamel.yaml.clib>=0.2.15 in c:\LLM\ch03_venv\Lib\site-packages (from ruamel.yaml<0.19.0,>=0.17.28->hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.15)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests>=2.20.0->speechbrain>=0.5.14->pyannote.audio==3.1.1) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests>=2.20.0->speechbrain>=0.5.14->pyannote.audio==3.1.1) (2.6.3)
Requirement already satisfied: greenlet>=1 in c:\LLM\ch03_venv\Lib\site-packages (from sqlalchemy>=1.4.2->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->pyannote.audio==3.1.1) (1.3.0)
Requirement already satisfied: protobuf>=3.20 in c:\LLM\ch03_venv\Lib\site-packages (from tensorboardX>=2.6->pyannote.audio==3.1.1) (6.33.6)
Requirement already satisfied: julius<0.3,>=0.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (0.2.7)
Requirement already satisfied: torch-pitch-shift>=1.2.2 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.2.5)
Requirement already satisfied: primePy>=1.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-pitch-shift>=1.2.2->torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch>=2.0.0->pyannote.audio==3.1.1) (3.0.3)
Requirement already satisfied: click>=8.2.1 in c:\LLM\ch03_venv\Lib\site-packages (from typer->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from typer->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\LLM\ch03_venv\Lib\site-packages (from typer->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.0.4)
Using cached pyannote.audio-3.1.1-py2.py3-none-any.whl (208 kB)
Using cached torch-2.11.0-cp312-cp312-win_amd64.whl (114.6 MB)
Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
Using cached torchaudio-2.11.0-cp312-cp312-win_amd64.whl (328 kB)
Installing collected packages: torchaudio, numpy, torch, pyannote.audio

   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
  Attempting uninstall: numpy
   ---------------------------------------- 0/4 [torchaudio]
    Found existing installation: numpy 1.26.0
   ---------------------------------------- 0/4 [torchaudio]
   ---------- ----------------------------- 1/4 [numpy]
    Uninstalling numpy-1.26.0:
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
      Successfully uninstalled numpy-1.26.0
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
  WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~.mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~.mpy'.
  You can safely remove it manually.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Collecting numpy==1.26
  Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl (15.5 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.4
    Uninstalling numpy-2.4.4:
      Successfully uninstalled numpy-2.4.4
Successfully installed numpy-1.26.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyannote-core 6.0.1 requires numpy>=2.0, but you have numpy 1.26.0 which is incompatible.
pyannote-metrics 4.0.0 requires numpy>=2.2.2, but you have numpy 1.26.0 which is incompatible.
scipy 1.17.1 requires numpy<2.7,>=1.26.4, but you have numpy 1.26.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

In [1]:
import torchaudio
print(torchaudio.__version__) 
# 여기서 2.2.2 라고 나와야 성공입니다!

2.11.0+cpu

In [4]:
# 1. 충돌이 발생하는 허깅페이스 허브 삭제 후 구버전 설치
%pip uninstall huggingface_hub -y
%pip install huggingface_hub==0.23.5

# 2. 커널 재시작 (Restart Kernel) 버튼을 꼭 눌러주세요!

Found existing installation: huggingface_hub 1.12.0
Uninstalling huggingface_hub-1.12.0:
  Successfully uninstalled huggingface_hub-1.12.0
Note: you may need to restart the kernel to use updated packages.
Collecting huggingface_hub==0.23.5
  Downloading huggingface_hub-0.23.5-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.23.5) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.23.5) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.23.5) (26.2)
Requirement already satisfied: pyyaml>=5.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.23.5) (6.0.3)
Requirement already satisfied: requests in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.23.5) (2.33.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.23.5) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.23.5) (4.15.0)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface_hub==0.23.5) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.23.5) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.23.5) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.23.5) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.23.5) (2026.4.22)
Downloading huggingface_hub-0.23.5-py3-none-any.whl (402 kB)
Installing collected packages: huggingface_hub
Successfully installed huggingface_hub-0.23.5
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
datasets 4.8.5 requires huggingface-hub<2.0,>=0.25.0, but you have huggingface-hub 0.23.5 which is incompatible.
transformers 5.7.0 requires huggingface-hub<2.0,>=1.5.0, but you have huggingface-hub 0.23.5 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

In [2]:
# 1. 꼬여있는 패키지 삭제
%pip uninstall pyannote.audio huggingface_hub torchaudio torch -y

# 2. 검증된 황금 밸런스 버전으로 재설치
# huggingface_hub 0.25.0은 'is_offline_mode'와 'token' 인자를 모두 지원합니다.
%pip install huggingface_hub==0.25.0
%pip install torch==2.2.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118
%pip install pyannote.audio==3.1.1
%pip install numpy==1.26

Found existing installation: pyannote.audio 3.1.1
Uninstalling pyannote.audio-3.1.1:
  Successfully uninstalled pyannote.audio-3.1.1
Found existing installation: huggingface-hub 0.23.5
Uninstalling huggingface-hub-0.23.5:
  Successfully uninstalled huggingface-hub-0.23.5
Found existing installation: torchaudio 2.11.0
Uninstalling torchaudio-2.11.0:
  Successfully uninstalled torchaudio-2.11.0
Found existing installation: torch 2.11.0
Uninstalling torch-2.11.0:
  Successfully uninstalled torch-2.11.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~~rchaudio'.
You can safely remove it manually.
WARNING: Failed to remove contents in a temporary directory 'C:\Users\lsh8389\AppData\Local\Temp\pip-uninstall-xf3l6x6o'.
You can safely remove it manually.
WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\torch\~~b'.
You can safely remove it manually.

Collecting huggingface_hub==0.25.0
  Downloading huggingface_hub-0.25.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (6.0.3)
Requirement already satisfied: requests in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (2.33.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (4.15.0)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface_hub==0.25.0) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (2026.4.22)
Downloading huggingface_hub-0.25.0-py3-none-any.whl (436 kB)
Installing collected packages: huggingface_hub
Successfully installed huggingface_hub-0.25.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
accelerate 1.13.0 requires torch>=2.0.0, which is not installed.
speechbrain 1.1.0 requires torch>=2.1.0, which is not installed.
speechbrain 1.1.0 requires torchaudio>=2.1.0, which is not installed.
transformers 5.7.0 requires huggingface-hub<2.0,>=1.5.0, but you have huggingface-hub 0.25.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch==2.2.2
  Downloading torch-2.2.2%2Bcu118-cp312-cp312-win_amd64.whl (2704.2 MB)
     ---------------------------------------- 0.0/2.7 GB ? eta -:--:--
     ---------------------------------------- 0.0/2.7 GB 99.5 MB/s eta 0:00:27
      --------------------------------------- 0.0/2.7 GB 97.5 MB/s eta 0:00:28
      --------------------------------------- 0.1/2.7 GB 104.2 MB/s eta 0:00:26
     - -------------------------------------- 0.1/2.7 GB 104.6 MB/s eta 0:00:26
     - -------------------------------------- 0.1/2.7 GB 104.9 MB/s eta 0:00:25
     - -------------------------------------- 0.1/2.7 GB 104.7 MB/s eta 0:00:25
     -- ------------------------------------- 0.2/2.7 GB 105.0 MB/s eta 0:00:25
     -- ------------------------------------- 0.2/2.7 GB 106.2 MB/s eta 0:00:24
     -- ------------------------------------- 0.2/2.7 GB 106.3 MB/s eta 0:00:24
     --- ------------------------------------ 0.2/2.7 GB 105.8 MB/s eta 0:00:24
     --- ------------------------------------ 0.2/2.7 GB 106.1 MB/s eta 0:00:24
     --- ------------------------------------ 0.3/2.7 GB 107.5 MB/s eta 0:00:23
     ---- ----------------------------------- 0.3/2.7 GB 107.5 MB/s eta 0:00:23
     ---- ----------------------------------- 0.3/2.7 GB 108.1 MB/s eta 0:00:23
     ----- ---------------------------------- 0.3/2.7 GB 107.4 MB/s eta 0:00:23
     ----- ---------------------------------- 0.4/2.7 GB 107.5 MB/s eta 0:00:22
     ----- ---------------------------------- 0.4/2.7 GB 108.8 MB/s eta 0:00:22
     ------ --------------------------------- 0.4/2.7 GB 108.1 MB/s eta 0:00:22
     ------ --------------------------------- 0.4/2.7 GB 108.1 MB/s eta 0:00:22
     ------ --------------------------------- 0.5/2.7 GB 107.5 MB/s eta 0:00:21
     ------- -------------------------------- 0.5/2.7 GB 107.5 MB/s eta 0:00:21
     ------- -------------------------------- 0.5/2.7 GB 107.4 MB/s eta 0:00:21
     ------- -------------------------------- 0.5/2.7 GB 106.8 MB/s eta 0:00:21
     -------- ------------------------------- 0.5/2.7 GB 106.8 MB/s eta 0:00:21
     -------- ------------------------------- 0.6/2.7 GB 106.8 MB/s eta 0:00:21
     -------- ------------------------------- 0.6/2.7 GB 106.1 MB/s eta 0:00:20
     -------- ------------------------------- 0.6/2.7 GB 106.1 MB/s eta 0:00:20
     --------- ------------------------------ 0.6/2.7 GB 106.1 MB/s eta 0:00:20
     --------- ------------------------------ 0.6/2.7 GB 104.8 MB/s eta 0:00:20
     --------- ------------------------------ 0.7/2.7 GB 104.8 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 104.8 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 105.4 MB/s eta 0:00:19
     ---------- ----------------------------- 0.7/2.7 GB 104.8 MB/s eta 0:00:19
     ----------- ---------------------------- 0.8/2.7 GB 104.1 MB/s eta 0:00:19
     ----------- ---------------------------- 0.8/2.7 GB 102.9 MB/s eta 0:00:19
     ----------- ---------------------------- 0.8/2.7 GB 104.1 MB/s eta 0:00:19
     ------------ --------------------------- 0.8/2.7 GB 102.8 MB/s eta 0:00:19
     ------------ --------------------------- 0.8/2.7 GB 102.2 MB/s eta 0:00:19
     ------------ --------------------------- 0.9/2.7 GB 102.2 MB/s eta 0:00:18
     ------------- -------------------------- 0.9/2.7 GB 101.6 MB/s eta 0:00:18
     ------------- -------------------------- 0.9/2.7 GB 104.1 MB/s eta 0:00:18
     ------------- -------------------------- 0.9/2.7 GB 103.4 MB/s eta 0:00:18
     -------------- ------------------------- 1.0/2.7 GB 101.0 MB/s eta 0:00:18
     -------------- ------------------------- 1.0/2.7 GB 96.9 MB/s eta 0:00:18
     -------------- ------------------------- 1.0/2.7 GB 92.1 MB/s eta 0:00:19
     -------------- ------------------------- 1.0/2.7 GB 86.8 MB/s eta 0:00:20
     -------------- ------------------------- 1.0/2.7 GB 83.4 MB/s eta 0:00:21
     -------------- ------------------------- 1.0/2.7 GB 78.7 MB/s eta 0:00:22
     -------------- ------------------------- 1.0/2.7 GB 74.8 MB/s eta 0:00:23
     -------------- ------------------------- 1.0/2.7 GB 72.2 MB/s eta 0:00:24
     -------------- ------------------------- 1.0/2.7 GB 69.8 MB/s eta 0:00:25
     --------------- ------------------------ 1.0/2.7 GB 67.3 MB/s eta 0:00:26
     --------------- ------------------------ 1.0/2.7 GB 64.7 MB/s eta 0:00:26
     --------------- ------------------------ 1.0/2.7 GB 62.8 MB/s eta 0:00:27
     --------------- ------------------------ 1.0/2.7 GB 60.5 MB/s eta 0:00:28
     --------------- ------------------------ 1.0/2.7 GB 58.4 MB/s eta 0:00:29
     --------------- ------------------------ 1.1/2.7 GB 57.0 MB/s eta 0:00:30
     --------------- ------------------------ 1.1/2.7 GB 55.1 MB/s eta 0:00:30
     --------------- ------------------------ 1.1/2.7 GB 53.4 MB/s eta 0:00:31
     --------------- ------------------------ 1.1/2.7 GB 51.9 MB/s eta 0:00:32
     --------------- ------------------------ 1.1/2.7 GB 50.3 MB/s eta 0:00:33
     ---------------- ----------------------- 1.1/2.7 GB 49.4 MB/s eta 0:00:33
     ---------------- ----------------------- 1.1/2.7 GB 48.2 MB/s eta 0:00:34
     ---------------- ----------------------- 1.1/2.7 GB 47.2 MB/s eta 0:00:34
     ---------------- ----------------------- 1.1/2.7 GB 46.0 MB/s eta 0:00:35
     ---------------- ----------------------- 1.1/2.7 GB 44.8 MB/s eta 0:00:36
     ---------------- ----------------------- 1.1/2.7 GB 43.6 MB/s eta 0:00:37
     ---------------- ----------------------- 1.1/2.7 GB 43.0 MB/s eta 0:00:37
     ---------------- ----------------------- 1.1/2.7 GB 43.0 MB/s eta 0:00:37
     ---------------- ----------------------- 1.1/2.7 GB 40.5 MB/s eta 0:00:39
     ---------------- ----------------------- 1.1/2.7 GB 39.5 MB/s eta 0:00:40
     ----------------- ---------------------- 1.2/2.7 GB 39.4 MB/s eta 0:00:39
     ----------------- ---------------------- 1.2/2.7 GB 39.6 MB/s eta 0:00:39
     ----------------- ---------------------- 1.2/2.7 GB 38.7 MB/s eta 0:00:39
     ----------------- ---------------------- 1.2/2.7 GB 38.2 MB/s eta 0:00:40
     ------------------ --------------------- 1.2/2.7 GB 38.0 MB/s eta 0:00:40
     ------------------ --------------------- 1.2/2.7 GB 38.1 MB/s eta 0:00:39
     ------------------ --------------------- 1.2/2.7 GB 38.5 MB/s eta 0:00:39
     ------------------ --------------------- 1.2/2.7 GB 38.7 MB/s eta 0:00:38
     ------------------ --------------------- 1.3/2.7 GB 39.4 MB/s eta 0:00:37
     ------------------ --------------------- 1.3/2.7 GB 40.0 MB/s eta 0:00:37
     ------------------ --------------------- 1.3/2.7 GB 40.3 MB/s eta 0:00:36
     ------------------ --------------------- 1.3/2.7 GB 40.9 MB/s eta 0:00:35
     ------------------- -------------------- 1.3/2.7 GB 41.2 MB/s eta 0:00:35
     ------------------- -------------------- 1.3/2.7 GB 41.8 MB/s eta 0:00:34
     ------------------- -------------------- 1.3/2.7 GB 41.8 MB/s eta 0:00:34
     ------------------- -------------------- 1.3/2.7 GB 42.0 MB/s eta 0:00:34
     ------------------- -------------------- 1.3/2.7 GB 42.3 MB/s eta 0:00:33
     ------------------- -------------------- 1.3/2.7 GB 42.9 MB/s eta 0:00:33
     ------------------- -------------------- 1.3/2.7 GB 43.2 MB/s eta 0:00:32
     ------------------- -------------------- 1.3/2.7 GB 43.2 MB/s eta 0:00:32
     -------------------- ------------------- 1.4/2.7 GB 43.5 MB/s eta 0:00:32
     -------------------- ------------------- 1.4/2.7 GB 43.6 MB/s eta 0:00:31
     -------------------- ------------------- 1.4/2.7 GB 44.0 MB/s eta 0:00:31
     -------------------- ------------------- 1.4/2.7 GB 44.5 MB/s eta 0:00:30
     -------------------- ------------------- 1.4/2.7 GB 44.0 MB/s eta 0:00:30
     -------------------- ------------------- 1.4/2.7 GB 47.9 MB/s eta 0:00:28
     -------------------- ------------------- 1.4/2.7 GB 46.7 MB/s eta 0:00:28
     -------------------- ------------------- 1.4/2.7 GB 45.5 MB/s eta 0:00:29
     -------------------- ------------------- 1.4/2.7 GB 44.5 MB/s eta 0:00:29
     --------------------- ------------------ 1.4/2.7 GB 43.6 MB/s eta 0:00:30
     --------------------- ------------------ 1.4/2.7 GB 42.6 MB/s eta 0:00:30
     --------------------- ------------------ 1.4/2.7 GB 41.9 MB/s eta 0:00:31
     --------------------- ------------------ 1.5/2.7 GB 41.5 MB/s eta 0:00:31
     --------------------- ------------------ 1.5/2.7 GB 41.3 MB/s eta 0:00:31
     --------------------- ------------------ 1.5/2.7 GB 41.2 MB/s eta 0:00:30
     --------------------- ------------------ 1.5/2.7 GB 41.0 MB/s eta 0:00:30
     ---------------------- ----------------- 1.5/2.7 GB 40.8 MB/s eta 0:00:30
     ---------------------- ----------------- 1.5/2.7 GB 41.1 MB/s eta 0:00:30
     ---------------------- ----------------- 1.5/2.7 GB 41.0 MB/s eta 0:00:30
     ---------------------- ----------------- 1.5/2.7 GB 41.2 MB/s eta 0:00:29
     ---------------------- ----------------- 1.5/2.7 GB 41.0 MB/s eta 0:00:29
     ---------------------- ----------------- 1.5/2.7 GB 41.0 MB/s eta 0:00:29
     ---------------------- ----------------- 1.5/2.7 GB 41.1 MB/s eta 0:00:29
     ---------------------- ----------------- 1.6/2.7 GB 41.1 MB/s eta 0:00:29
     ----------------------- ---------------- 1.6/2.7 GB 41.3 MB/s eta 0:00:28
     ----------------------- ---------------- 1.6/2.7 GB 41.4 MB/s eta 0:00:28
     ----------------------- ---------------- 1.6/2.7 GB 41.5 MB/s eta 0:00:28
     ----------------------- ---------------- 1.6/2.7 GB 41.7 MB/s eta 0:00:27
     ----------------------- ---------------- 1.6/2.7 GB 41.6 MB/s eta 0:00:27
     ----------------------- ---------------- 1.6/2.7 GB 41.9 MB/s eta 0:00:27
     ----------------------- ---------------- 1.6/2.7 GB 42.0 MB/s eta 0:00:26
     ----------------------- ---------------- 1.6/2.7 GB 41.5 MB/s eta 0:00:27
     ------------------------ --------------- 1.6/2.7 GB 42.3 MB/s eta 0:00:26
     ------------------------ --------------- 1.6/2.7 GB 42.4 MB/s eta 0:00:25
     ------------------------ --------------- 1.7/2.7 GB 43.0 MB/s eta 0:00:25
     ------------------------ --------------- 1.7/2.7 GB 43.2 MB/s eta 0:00:25
     ------------------------ --------------- 1.7/2.7 GB 44.1 MB/s eta 0:00:24
     ------------------------ --------------- 1.7/2.7 GB 44.5 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 44.6 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 44.8 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 45.1 MB/s eta 0:00:22
     ------------------------- -------------- 1.7/2.7 GB 45.3 MB/s eta 0:00:22
     ------------------------- -------------- 1.7/2.7 GB 45.4 MB/s eta 0:00:22
     ------------------------- -------------- 1.7/2.7 GB 45.7 MB/s eta 0:00:22
     ------------------------- -------------- 1.8/2.7 GB 45.8 MB/s eta 0:00:21
     -------------------------- ------------- 1.8/2.7 GB 45.7 MB/s eta 0:00:21
     -------------------------- ------------- 1.8/2.7 GB 46.2 MB/s eta 0:00:21
     -------------------------- ------------- 1.8/2.7 GB 46.4 MB/s eta 0:00:20
     -------------------------- ------------- 1.8/2.7 GB 46.8 MB/s eta 0:00:20
     -------------------------- ------------- 1.8/2.7 GB 46.8 MB/s eta 0:00:20
     -------------------------- ------------- 1.8/2.7 GB 46.9 MB/s eta 0:00:19
     -------------------------- ------------- 1.8/2.7 GB 46.9 MB/s eta 0:00:19
     --------------------------- ------------ 1.8/2.7 GB 47.2 MB/s eta 0:00:19
     --------------------------- ------------ 1.8/2.7 GB 46.8 MB/s eta 0:00:19
     --------------------------- ------------ 1.9/2.7 GB 46.8 MB/s eta 0:00:19
     --------------------------- ------------ 1.9/2.7 GB 46.8 MB/s eta 0:00:19
     --------------------------- ------------ 1.9/2.7 GB 46.4 MB/s eta 0:00:19
     --------------------------- ------------ 1.9/2.7 GB 45.8 MB/s eta 0:00:19
     --------------------------- ------------ 1.9/2.7 GB 45.7 MB/s eta 0:00:19
     --------------------------- ------------ 1.9/2.7 GB 45.7 MB/s eta 0:00:18
     ---------------------------- ----------- 1.9/2.7 GB 45.2 MB/s eta 0:00:18
     ---------------------------- ----------- 1.9/2.7 GB 45.1 MB/s eta 0:00:18
     ---------------------------- ----------- 1.9/2.7 GB 44.8 MB/s eta 0:00:18
     ---------------------------- ----------- 1.9/2.7 GB 44.3 MB/s eta 0:00:18
     ---------------------------- ----------- 1.9/2.7 GB 43.4 MB/s eta 0:00:18
     ---------------------------- ----------- 1.9/2.7 GB 42.6 MB/s eta 0:00:19
     ---------------------------- ----------- 1.9/2.7 GB 41.9 MB/s eta 0:00:19
     ---------------------------- ----------- 1.9/2.7 GB 41.5 MB/s eta 0:00:19
     ---------------------------- ----------- 2.0/2.7 GB 41.2 MB/s eta 0:00:19
     ---------------------------- ----------- 2.0/2.7 GB 40.8 MB/s eta 0:00:19
     ----------------------------- ---------- 2.0/2.7 GB 40.5 MB/s eta 0:00:19
     ----------------------------- ---------- 2.0/2.7 GB 40.1 MB/s eta 0:00:19
     ----------------------------- ---------- 2.0/2.7 GB 40.1 MB/s eta 0:00:18
     ----------------------------- ---------- 2.0/2.7 GB 39.8 MB/s eta 0:00:18
     ----------------------------- ---------- 2.0/2.7 GB 39.7 MB/s eta 0:00:18
     ----------------------------- ---------- 2.0/2.7 GB 39.8 MB/s eta 0:00:18
     ----------------------------- ---------- 2.0/2.7 GB 40.0 MB/s eta 0:00:18
     ----------------------------- ---------- 2.0/2.7 GB 40.0 MB/s eta 0:00:18
     ----------------------------- ---------- 2.0/2.7 GB 40.0 MB/s eta 0:00:18
     ------------------------------ --------- 2.0/2.7 GB 38.7 MB/s eta 0:00:18
     ------------------------------ --------- 2.1/2.7 GB 39.5 MB/s eta 0:00:17
     ------------------------------ --------- 2.1/2.7 GB 39.3 MB/s eta 0:00:17
     ------------------------------ --------- 2.1/2.7 GB 39.1 MB/s eta 0:00:17
     ------------------------------ --------- 2.1/2.7 GB 39.1 MB/s eta 0:00:17
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: Exception:
Traceback (most recent call last):
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 897, in _error_catcher
    yield
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 1022, in _raw_read
    data = self._fp_read(amt, read1=read1) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 1005, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 104, in read
    self.__buf.write(data)
  File "C:\Users\lsh8389\AppData\Local\Programs\Python\Python312\Lib\tempfile.py", line 499, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 109, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\cli\base_command.py", line 102, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\cli\req_command.py", line 101, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\commands\install.py", line 479, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 99, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 601, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 434, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\resolvelib\resolvers\resolution.py", line 150, in _add_to_criteria
    if not criterion.candidates:
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 194, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 165, in __bool__
    self._bool = any(self)
                 ^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 149, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
                       ^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 39, in _iter_built
    candidate = func()
                ^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 182, in _make_candidate_from_link
    base: BaseCandidate | None = self._make_base_candidate_from_link(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 326, in __init__
    super().__init__(
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 168, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 246, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 337, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 542, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 613, in _prepare_linked_requirement
    local_file = unpack_url(
                 ^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 180, in unpack_url
    file = get_http_url(
           ^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\operations\prepare.py", line 121, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\network\download.py", line 193, in __call__
    self._process_response(download, resp)
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\network\download.py", line 210, in _process_response
    for chunk in chunks:
                 ^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 69, in _rich_download_progress_bar
    for chunk in iterable:
                 ^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_internal\network\utils.py", line 65, in response_chunks
    for chunk in response.raw.stream(
                 ^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 1251, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 1106, in read
    data = self._raw_read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 1021, in _raw_read
    with self._error_catcher():
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lsh8389\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "c:\LLM\ch03_venv\Lib\site-packages\pip\_vendor\urllib3\response.py", line 924, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: OSError(28, 'No space left on device')", OSError(28, 'No space left on device'))

Collecting pyannote.audio==3.1.1
  Using cached pyannote.audio-3.1.1-py2.py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: asteroid-filterbanks>=0.4 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.4.0)
Requirement already satisfied: einops>=0.6.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.25.0)
Requirement already satisfied: lightning>=2.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: omegaconf<3.0,>=2.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.3.0)
Requirement already satisfied: pyannote.core>=5.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.0.1)
Requirement already satisfied: pyannote.database>=5.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.1.1)
Requirement already satisfied: pyannote.metrics>=3.2 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pyannote.pipeline>=3.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pytorch-metric-learning>=2.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.9.0)
Requirement already satisfied: rich>=12.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (15.0.0)
Requirement already satisfied: semver>=3.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (3.0.4)
Requirement already satisfied: soundfile>=0.12.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.13.1)
Requirement already satisfied: speechbrain>=0.5.14 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.1.0)
Requirement already satisfied: tensorboardX>=2.6 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.5)
Collecting torch>=2.0.0 (from pyannote.audio==3.1.1)
  Using cached torch-2.11.0-cp312-cp312-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: torch-audiomentations>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.12.0)
Collecting torchaudio>=2.0.0 (from pyannote.audio==3.1.1)
  Using cached torchaudio-2.11.0-cp312-cp312-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: torchmetrics>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.9.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (6.0.3)
Requirement already satisfied: numpy in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (1.26.0)
Requirement already satisfied: typing-extensions in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (4.15.0)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (26.2)
Requirement already satisfied: requests in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2.33.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (4.67.3)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (0.15.3)
Requirement already satisfied: pytorch-lightning in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\LLM\ch03_venv\Lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13.5)
Requirement already satisfied: setuptools<82 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.1.6)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.23.0)
Requirement already satisfied: idna>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13)
Collecting numpy (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1)
  Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: pandas>=2.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (3.0.2)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2026.2)
Requirement already satisfied: scikit-learn>=1.6.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: scipy>=1.15.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.17.1)
Requirement already satisfied: optuna>=4.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.18.4)
Requirement already satisfied: colorlog in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (2.0.49)
Requirement already satisfied: Mako in c:\LLM\ch03_venv\Lib\site-packages (from alembic>=1.5.0->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.3.12)
Requirement already satisfied: six>=1.5 in c:\LLM\ch03_venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\LLM\ch03_venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->pyannote.audio==3.1.1) (0.1.2)
Requirement already satisfied: joblib>=1.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (3.6.0)
Requirement already satisfied: cffi>=1.0 in c:\LLM\ch03_venv\Lib\site-packages (from soundfile>=0.12.1->pyannote.audio==3.1.1) (2.0.0)
Requirement already satisfied: pycparser in c:\LLM\ch03_venv\Lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->pyannote.audio==3.1.1) (3.0)
Requirement already satisfied: hyperpyyaml>=0.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (1.2.3)
Requirement already satisfied: sentencepiece>=0.1.91 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.1)
Requirement already satisfied: ruamel.yaml<0.19.0,>=0.17.28 in c:\LLM\ch03_venv\Lib\site-packages (from hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.18.17)
Requirement already satisfied: ruamel.yaml.clib>=0.2.15 in c:\LLM\ch03_venv\Lib\site-packages (from ruamel.yaml<0.19.0,>=0.17.28->hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.15)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.4.22)
Requirement already satisfied: greenlet>=1 in c:\LLM\ch03_venv\Lib\site-packages (from sqlalchemy>=1.4.2->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->pyannote.audio==3.1.1) (1.3.0)
Requirement already satisfied: protobuf>=3.20 in c:\LLM\ch03_venv\Lib\site-packages (from tensorboardX>=2.6->pyannote.audio==3.1.1) (6.33.6)
Requirement already satisfied: julius<0.3,>=0.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (0.2.7)
Requirement already satisfied: torch-pitch-shift>=1.2.2 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.2.5)
Requirement already satisfied: primePy>=1.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-pitch-shift>=1.2.2->torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch>=2.0.0->pyannote.audio==3.1.1) (3.0.3)
Using cached pyannote.audio-3.1.1-py2.py3-none-any.whl (208 kB)
Using cached torch-2.11.0-cp312-cp312-win_amd64.whl (114.6 MB)
Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
Using cached torchaudio-2.11.0-cp312-cp312-win_amd64.whl (328 kB)
Installing collected packages: torchaudio, numpy, torch, pyannote.audio

   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
  Attempting uninstall: numpy
   ---------------------------------------- 0/4 [torchaudio]
    Found existing installation: numpy 1.26.0
   ---------------------------------------- 0/4 [torchaudio]
   ---------- ----------------------------- 1/4 [numpy]
    Uninstalling numpy-1.26.0:
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
      Successfully uninstalled numpy-1.26.0
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]
   -------------------- ------------------- 2/4 [torch]

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
  WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~=mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~=mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 5.7.0 requires huggingface-hub<2.0,>=1.5.0, but you have huggingface-hub 0.25.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Collecting numpy==1.26
  Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl (15.5 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.4
    Uninstalling numpy-2.4.4:
      Successfully uninstalled numpy-2.4.4
Successfully installed numpy-1.26.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyannote-core 6.0.1 requires numpy>=2.0, but you have numpy 1.26.0 which is incompatible.
pyannote-metrics 4.0.0 requires numpy>=2.2.2, but you have numpy 1.26.0 which is incompatible.
scipy 1.17.1 requires numpy<2.7,>=1.26.4, but you have numpy 1.26.0 which is incompatible.
transformers 5.7.0 requires huggingface-hub<2.0,>=1.5.0, but you have huggingface-hub 0.25.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

In [3]:
# 1. 기존 설치 시도 흔적 삭제
%pip uninstall torch torchaudio pyannote.audio -y

# 2. 조금 더 가벼운 버전으로 재설치
%pip install torch==2.2.2 torchaudio==2.2.2 
%pip install pyannote.audio==3.1.1
%pip install huggingface_hub==0.25.0
%pip install numpy==1.26

Found existing installation: torch 2.11.0
Uninstalling torch-2.11.0:
  Successfully uninstalled torch-2.11.0
Found existing installation: torchaudio 2.11.0
Uninstalling torchaudio-2.11.0:
  Successfully uninstalled torchaudio-2.11.0
Found existing installation: pyannote.audio 3.1.1
Uninstalling pyannote.audio-3.1.1:
  Successfully uninstalled pyannote.audio-3.1.1
Note: you may need to restart the kernel to use updated packages.
Collecting torch==2.2.2
  Downloading torch-2.2.2-cp312-cp312-win_amd64.whl.metadata (26 kB)
Collecting torchaudio==2.2.2
  Downloading torchaudio-2.2.2-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (3.29.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (4.15.0)
Requirement already satisfied: sympy in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (1.14.0)
Requirement already satisfied: networkx in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (3.1.6)
Requirement already satisfied: fsspec in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (2026.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch==2.2.2) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy->torch==2.2.2) (1.3.0)
Downloading torch-2.2.2-cp312-cp312-win_amd64.whl (198.5 MB)
   ---------------------------------------- 0.0/198.5 MB ? eta -:--:--
    --------------------------------------- 3.9/198.5 MB 26.2 MB/s eta 0:00:08
   - -------------------------------------- 9.4/198.5 MB 26.7 MB/s eta 0:00:08
   ----- ---------------------------------- 25.4/198.5 MB 47.4 MB/s eta 0:00:04
   -------- ------------------------------- 43.3/198.5 MB 58.6 MB/s eta 0:00:03
   ----------- ---------------------------- 55.3/198.5 MB 56.8 MB/s eta 0:00:03
   -------------- ------------------------- 74.2/198.5 MB 62.3 MB/s eta 0:00:02
   ----------------- ---------------------- 86.0/198.5 MB 61.0 MB/s eta 0:00:02
   ------------------- ------------------- 101.7/198.5 MB 63.1 MB/s eta 0:00:02
   ----------------------- --------------- 118.2/198.5 MB 64.5 MB/s eta 0:00:02
   --------------------------- ----------- 138.9/198.5 MB 67.7 MB/s eta 0:00:01
   ---------------------------- ---------- 145.2/198.5 MB 63.6 MB/s eta 0:00:01
   ------------------------------ -------- 153.6/198.5 MB 61.0 MB/s eta 0:00:01
   ---------------------------------- ---- 173.3/198.5 MB 63.3 MB/s eta 0:00:01
   ------------------------------------- - 191.9/198.5 MB 65.2 MB/s eta 0:00:01
   --------------------------------------  198.4/198.5 MB 63.7 MB/s eta 0:00:01
   --------------------------------------  198.4/198.5 MB 63.7 MB/s eta 0:00:01
   --------------------------------------  198.4/198.5 MB 63.7 MB/s eta 0:00:01
   ---------------------------------------- 198.5/198.5 MB 54.5 MB/s  0:00:03
Downloading torchaudio-2.2.2-cp312-cp312-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 2.4/2.4 MB 67.4 MB/s  0:00:00
Installing collected packages: torch, torchaudio

   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Collecting pyannote.audio==3.1.1
  Downloading pyannote.audio-3.1.1-py2.py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: asteroid-filterbanks>=0.4 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.4.0)
Requirement already satisfied: einops>=0.6.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.25.0)
Requirement already satisfied: lightning>=2.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: omegaconf<3.0,>=2.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.3.0)
Requirement already satisfied: pyannote.core>=5.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.0.1)
Requirement already satisfied: pyannote.database>=5.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.1.1)
Requirement already satisfied: pyannote.metrics>=3.2 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pyannote.pipeline>=3.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pytorch-metric-learning>=2.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.9.0)
Requirement already satisfied: rich>=12.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (15.0.0)
Requirement already satisfied: semver>=3.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (3.0.4)
Requirement already satisfied: soundfile>=0.12.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.13.1)
Requirement already satisfied: speechbrain>=0.5.14 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.1.0)
Requirement already satisfied: tensorboardX>=2.6 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.5)
Requirement already satisfied: torch>=2.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.2.2)
Requirement already satisfied: torch-audiomentations>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.12.0)
Requirement already satisfied: torchaudio>=2.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.2.2)
Requirement already satisfied: torchmetrics>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.9.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (6.0.3)
Requirement already satisfied: numpy in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (1.26.0)
Requirement already satisfied: typing-extensions in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (4.15.0)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (26.2)
Requirement already satisfied: requests in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2.33.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (4.67.3)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (0.15.3)
Requirement already satisfied: pytorch-lightning in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\LLM\ch03_venv\Lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13.5)
Requirement already satisfied: sympy in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (1.14.0)
Requirement already satisfied: networkx in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.1.6)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.23.0)
Requirement already satisfied: idna>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13)
Collecting numpy (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1)
  Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: pandas>=2.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (3.0.2)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2026.2)
Requirement already satisfied: scikit-learn>=1.6.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: scipy>=1.15.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.17.1)
Requirement already satisfied: optuna>=4.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.18.4)
Requirement already satisfied: colorlog in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (2.0.49)
Requirement already satisfied: Mako in c:\LLM\ch03_venv\Lib\site-packages (from alembic>=1.5.0->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.3.12)
Requirement already satisfied: six>=1.5 in c:\LLM\ch03_venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\LLM\ch03_venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->pyannote.audio==3.1.1) (0.1.2)
Requirement already satisfied: joblib>=1.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (3.6.0)
Requirement already satisfied: cffi>=1.0 in c:\LLM\ch03_venv\Lib\site-packages (from soundfile>=0.12.1->pyannote.audio==3.1.1) (2.0.0)
Requirement already satisfied: pycparser in c:\LLM\ch03_venv\Lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->pyannote.audio==3.1.1) (3.0)
Requirement already satisfied: hyperpyyaml>=0.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (1.2.3)
Requirement already satisfied: sentencepiece>=0.1.91 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.1)
Requirement already satisfied: ruamel.yaml<0.19.0,>=0.17.28 in c:\LLM\ch03_venv\Lib\site-packages (from hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.18.17)
Requirement already satisfied: ruamel.yaml.clib>=0.2.15 in c:\LLM\ch03_venv\Lib\site-packages (from ruamel.yaml<0.19.0,>=0.17.28->hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.15)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.4.22)
Requirement already satisfied: greenlet>=1 in c:\LLM\ch03_venv\Lib\site-packages (from sqlalchemy>=1.4.2->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (3.5.0)
Requirement already satisfied: protobuf>=3.20 in c:\LLM\ch03_venv\Lib\site-packages (from tensorboardX>=2.6->pyannote.audio==3.1.1) (6.33.6)
Requirement already satisfied: julius<0.3,>=0.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (0.2.7)
Requirement already satisfied: torch-pitch-shift>=1.2.2 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.2.5)
Requirement already satisfied: primePy>=1.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-pitch-shift>=1.2.2->torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch>=2.0.0->pyannote.audio==3.1.1) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy->torch>=2.0.0->pyannote.audio==3.1.1) (1.3.0)
Downloading pyannote.audio-3.1.1-py2.py3-none-any.whl (208 kB)
Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------  12.1/12.3 MB 68.6 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 55.1 MB/s  0:00:00
Installing collected packages: numpy, pyannote.audio

  Attempting uninstall: numpy

    Found existing installation: numpy 1.26.0

    Uninstalling numpy-1.26.0:

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
      Successfully uninstalled numpy-1.26.0
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pyannote.audio]
   -------------------- ------------------- 1/2 [pyannote.audio]
   -------------------- ------------------- 1/2 [pyannote.audio]
   -------------------- ------------------- 1/2 [pyannote.audio]
   -------------------- ------------------- 1/2 [pyannote.audio]
   -------------------- ------------------- 1/2 [pyannote.audio]
   -------------------- ------------------- 1/2 [pyannote.audio]
   -------------------- ------------------- 1/2 [pyannote.audio]
   -------------------- ------------------- 1/2 [pyannote.audio]
   ---------------------------------------- 2/2 [pyannote.audio]

Successfully installed numpy-2.4.4 pyannote.audio-3.1.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 5.7.0 requires huggingface-hub<2.0,>=1.5.0, but you have huggingface-hub 0.25.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Requirement already satisfied: huggingface_hub==0.25.0 in c:\LLM\ch03_venv\Lib\site-packages (0.25.0)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (6.0.3)
Requirement already satisfied: requests in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (2.33.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (4.15.0)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface_hub==0.25.0) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (2026.4.22)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Collecting numpy==1.26
  Downloading numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Downloading numpy-1.26.0-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------  15.5/15.5 MB 97.5 MB/s eta 0:00:01
   ---------------------------------------- 15.5/15.5 MB 75.1 MB/s  0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.4
    Uninstalling numpy-2.4.4:
      Successfully uninstalled numpy-2.4.4
Successfully installed numpy-1.26.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyannote-core 6.0.1 requires numpy>=2.0, but you have numpy 1.26.0 which is incompatible.
pyannote-metrics 4.0.0 requires numpy>=2.2.2, but you have numpy 1.26.0 which is incompatible.
scipy 1.17.1 requires numpy<2.7,>=1.26.4, but you have numpy 1.26.0 which is incompatible.
transformers 5.7.0 requires huggingface-hub<2.0,>=1.5.0, but you have huggingface-hub 0.25.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

In [1]:
# [1] 호환성 패치
import torchaudio
if not hasattr(torchaudio, 'set_audio_backend'):
    torchaudio.set_audio_backend = lambda x: None

# [2] 라이브러리 로드
from pyannote.audio import Pipeline
import torch

# [3] 모델 불러오기 (token 인자 사용)
pipeline = Pipeline.from_pretrained(
    "pyannote/speaker-diarization-3.1",
    token="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"
)

# [4] 장치 설정 및 실행
pipeline.to(torch.device("cpu"))
print("✅ 준비 완료! 화자 분리를 시작합니다.")

# 파일 경로가 맞는지 확인 (audio 폴더 안에 파일이 있어야 함)
diarization = pipeline("audio/lsy_audio_2023_58s.mp3")

# [5] 결과 저장
with open("audio/result.rttm", "w", encoding='utf-8') as rttm:
    diarization.write_rttm(rttm)

print("✨ 드디어 성공! 'audio/result.rttm' 파일이 생성되었습니다.")

c:\LLM\ch03_venv\Lib\site-packages\torchmetrics\__init__.py:31: UserWarning: A NumPy version >=1.26.4 and <2.7.0 is required for this version of SciPy (detected version 1.26.0)
  import scipy.signal
c:\LLM\ch03_venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[transformers] Disabling PyTorch because PyTorch >= 2.4 is required but found 2.2.2

ImportError: cannot import name 'is_offline_mode' from 'huggingface_hub' (c:\LLM\ch03_venv\Lib\site-packages\huggingface_hub\__init__.py)

In [2]:
# 1. 찌꺼기 제거
%pip uninstall torch torchaudio pyannote.audio huggingface_hub -y

# 2. 필수 패키지만 재설치 (현재 가장 안정적인 조합)
%pip install torch==2.2.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118
%pip install huggingface_hub==0.25.0
%pip install pyannote.audio==3.1.1

Found existing installation: torch 2.2.2
Uninstalling torch-2.2.2:
  Successfully uninstalled torch-2.2.2
Found existing installation: torchaudio 2.2.2
Uninstalling torchaudio-2.2.2:
  Successfully uninstalled torchaudio-2.2.2
Found existing installation: pyannote.audio 3.1.1
Uninstalling pyannote.audio-3.1.1:
  Successfully uninstalled pyannote.audio-3.1.1
Found existing installation: huggingface-hub 0.25.0
Uninstalling huggingface-hub-0.25.0:
  Successfully uninstalled huggingface-hub-0.25.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\Users\lsh8389\AppData\Local\Temp\pip-uninstall-891px4aj'.
You can safely remove it manually.
WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\torch\~.b'.
You can safely remove it manually.
WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~.rchaudio'.
You can safely remove it manually.

Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch==2.2.2
  Downloading torch-2.2.2%2Bcu118-cp312-cp312-win_amd64.whl (2704.2 MB)
     ---------------------------------------- 0.0/2.7 GB ? eta -:--:--
     ---------------------------------------- 0.0/2.7 GB 100.7 MB/s eta 0:00:27
      --------------------------------------- 0.0/2.7 GB 98.5 MB/s eta 0:00:28
      --------------------------------------- 0.1/2.7 GB 101.0 MB/s eta 0:00:27
     - -------------------------------------- 0.1/2.7 GB 101.9 MB/s eta 0:00:26
     - -------------------------------------- 0.1/2.7 GB 98.6 MB/s eta 0:00:27
     - -------------------------------------- 0.1/2.7 GB 97.3 MB/s eta 0:00:27
     -- ------------------------------------- 0.1/2.7 GB 98.7 MB/s eta 0:00:26
     -- ------------------------------------- 0.2/2.7 GB 99.2 MB/s eta 0:00:26
     -- ------------------------------------- 0.2/2.7 GB 100.1 MB/s eta 0:00:26
     --- ------------------------------------ 0.2/2.7 GB 100.8 MB/s eta 0:00:25
     --- ------------------------------------ 0.2/2.7 GB 101.2 MB/s eta 0:00:25
     --- ------------------------------------ 0.3/2.7 GB 101.1 MB/s eta 0:00:25
     ---- ----------------------------------- 0.3/2.7 GB 101.0 MB/s eta 0:00:25
     ---- ----------------------------------- 0.3/2.7 GB 101.0 MB/s eta 0:00:24
     ---- ----------------------------------- 0.3/2.7 GB 101.6 MB/s eta 0:00:24
     ----- ---------------------------------- 0.3/2.7 GB 101.6 MB/s eta 0:00:24
     ----- ---------------------------------- 0.4/2.7 GB 102.8 MB/s eta 0:00:23
     ----- ---------------------------------- 0.4/2.7 GB 104.8 MB/s eta 0:00:23
     ------ --------------------------------- 0.4/2.7 GB 105.4 MB/s eta 0:00:22
     ------ --------------------------------- 0.4/2.7 GB 104.8 MB/s eta 0:00:22
     ------ --------------------------------- 0.5/2.7 GB 105.4 MB/s eta 0:00:22
     ------- -------------------------------- 0.5/2.7 GB 105.4 MB/s eta 0:00:22
     ------- -------------------------------- 0.5/2.7 GB 105.4 MB/s eta 0:00:21
     ------- -------------------------------- 0.5/2.7 GB 106.1 MB/s eta 0:00:21
     -------- ------------------------------- 0.5/2.7 GB 106.8 MB/s eta 0:00:21
     -------- ------------------------------- 0.6/2.7 GB 106.8 MB/s eta 0:00:21
     -------- ------------------------------- 0.6/2.7 GB 106.1 MB/s eta 0:00:20
     --------- ------------------------------ 0.6/2.7 GB 105.4 MB/s eta 0:00:20
     --------- ------------------------------ 0.6/2.7 GB 104.8 MB/s eta 0:00:20
     --------- ------------------------------ 0.6/2.7 GB 103.5 MB/s eta 0:00:20
     --------- ------------------------------ 0.7/2.7 GB 102.8 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 102.8 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 102.2 MB/s eta 0:00:20
     ---------- ----------------------------- 0.7/2.7 GB 102.2 MB/s eta 0:00:20
     ----------- ---------------------------- 0.8/2.7 GB 102.2 MB/s eta 0:00:20
     ----------- ---------------------------- 0.8/2.7 GB 102.2 MB/s eta 0:00:19
     ----------- ---------------------------- 0.8/2.7 GB 102.2 MB/s eta 0:00:19
     ------------ --------------------------- 0.8/2.7 GB 101.0 MB/s eta 0:00:19
     ------------ --------------------------- 0.8/2.7 GB 101.0 MB/s eta 0:00:19
     ------------ --------------------------- 0.9/2.7 GB 101.6 MB/s eta 0:00:19
     ------------- -------------------------- 0.9/2.7 GB 102.2 MB/s eta 0:00:18
     ------------- -------------------------- 0.9/2.7 GB 104.8 MB/s eta 0:00:18
     ------------- -------------------------- 0.9/2.7 GB 104.8 MB/s eta 0:00:17
     -------------- ------------------------- 1.0/2.7 GB 104.1 MB/s eta 0:00:17
     -------------- ------------------------- 1.0/2.7 GB 104.1 MB/s eta 0:00:17
     -------------- ------------------------- 1.0/2.7 GB 104.1 MB/s eta 0:00:17
     --------------- ------------------------ 1.0/2.7 GB 104.1 MB/s eta 0:00:17
     --------------- ------------------------ 1.0/2.7 GB 104.1 MB/s eta 0:00:17
     --------------- ------------------------ 1.0/2.7 GB 96.4 MB/s eta 0:00:18
     --------------- ------------------------ 1.1/2.7 GB 96.3 MB/s eta 0:00:18
     ---------------- ----------------------- 1.1/2.7 GB 95.8 MB/s eta 0:00:17
     ---------------- ----------------------- 1.1/2.7 GB 96.4 MB/s eta 0:00:17
     ---------------- ----------------------- 1.1/2.7 GB 94.1 MB/s eta 0:00:17
     ---------------- ----------------------- 1.1/2.7 GB 90.1 MB/s eta 0:00:18
     ---------------- ----------------------- 1.1/2.7 GB 84.6 MB/s eta 0:00:19
     ---------------- ----------------------- 1.1/2.7 GB 81.0 MB/s eta 0:00:20
     ----------------- ---------------------- 1.2/2.7 GB 78.3 MB/s eta 0:00:20
     ----------------- ---------------------- 1.2/2.7 GB 75.2 MB/s eta 0:00:21
     ----------------- ---------------------- 1.2/2.7 GB 72.5 MB/s eta 0:00:22
     ----------------- ---------------------- 1.2/2.7 GB 70.1 MB/s eta 0:00:22
     ----------------- ---------------------- 1.2/2.7 GB 67.6 MB/s eta 0:00:23
     ----------------- ---------------------- 1.2/2.7 GB 65.5 MB/s eta 0:00:24
     ----------------- ---------------------- 1.2/2.7 GB 63.7 MB/s eta 0:00:24
     ----------------- ---------------------- 1.2/2.7 GB 61.6 MB/s eta 0:00:25
     ----------------- ---------------------- 1.2/2.7 GB 59.6 MB/s eta 0:00:25
     ----------------- ---------------------- 1.2/2.7 GB 56.8 MB/s eta 0:00:27
     ------------------ --------------------- 1.2/2.7 GB 54.4 MB/s eta 0:00:28
     ------------------ --------------------- 1.2/2.7 GB 52.5 MB/s eta 0:00:29
     ------------------ --------------------- 1.2/2.7 GB 51.9 MB/s eta 0:00:29
     ------------------ --------------------- 1.2/2.7 GB 51.9 MB/s eta 0:00:29
     ------------------ --------------------- 1.2/2.7 GB 48.2 MB/s eta 0:00:31
     ------------------ --------------------- 1.2/2.7 GB 48.2 MB/s eta 0:00:31
     ------------------ --------------------- 1.2/2.7 GB 44.0 MB/s eta 0:00:34
     ------------------ --------------------- 1.2/2.7 GB 44.0 MB/s eta 0:00:34
     ------------------ --------------------- 1.2/2.7 GB 44.0 MB/s eta 0:00:34
     ------------------ --------------------- 1.2/2.7 GB 40.3 MB/s eta 0:00:37
     ------------------ --------------------- 1.2/2.7 GB 40.1 MB/s eta 0:00:37
     ------------------ --------------------- 1.2/2.7 GB 40.1 MB/s eta 0:00:37
     ------------------ --------------------- 1.2/2.7 GB 40.1 MB/s eta 0:00:37
     ------------------ --------------------- 1.2/2.7 GB 40.1 MB/s eta 0:00:37
     ------------------ --------------------- 1.2/2.7 GB 34.8 MB/s eta 0:00:43
     ------------------ --------------------- 1.3/2.7 GB 34.6 MB/s eta 0:00:42
     ------------------ --------------------- 1.3/2.7 GB 34.6 MB/s eta 0:00:42
     ------------------- -------------------- 1.3/2.7 GB 35.5 MB/s eta 0:00:40
     ------------------- -------------------- 1.3/2.7 GB 35.5 MB/s eta 0:00:39
     ------------------- -------------------- 1.3/2.7 GB 35.5 MB/s eta 0:00:39
     -------------------- ------------------- 1.4/2.7 GB 35.4 MB/s eta 0:00:38
     -------------------- ------------------- 1.4/2.7 GB 35.1 MB/s eta 0:00:38
     -------------------- ------------------- 1.4/2.7 GB 35.9 MB/s eta 0:00:37
     -------------------- ------------------- 1.4/2.7 GB 37.2 MB/s eta 0:00:35
     --------------------- ------------------ 1.4/2.7 GB 37.6 MB/s eta 0:00:35
     --------------------- ------------------ 1.4/2.7 GB 38.6 MB/s eta 0:00:33
     --------------------- ------------------ 1.5/2.7 GB 39.4 MB/s eta 0:00:32
     --------------------- ------------------ 1.5/2.7 GB 40.8 MB/s eta 0:00:31
     --------------------- ------------------ 1.5/2.7 GB 44.9 MB/s eta 0:00:28
     ---------------------- ----------------- 1.5/2.7 GB 61.2 MB/s eta 0:00:20
     ---------------------- ----------------- 1.5/2.7 GB 80.6 MB/s eta 0:00:15
     ---------------------- ----------------- 1.5/2.7 GB 76.5 MB/s eta 0:00:16
     ---------------------- ----------------- 1.5/2.7 GB 74.2 MB/s eta 0:00:16
     ---------------------- ----------------- 1.5/2.7 GB 71.9 MB/s eta 0:00:17
     ---------------------- ----------------- 1.5/2.7 GB 69.5 MB/s eta 0:00:17
     ---------------------- ----------------- 1.6/2.7 GB 67.9 MB/s eta 0:00:17
     ----------------------- ---------------- 1.6/2.7 GB 66.0 MB/s eta 0:00:18
     ----------------------- ---------------- 1.6/2.7 GB 64.7 MB/s eta 0:00:18
     ----------------------- ---------------- 1.6/2.7 GB 62.5 MB/s eta 0:00:18
     ----------------------- ---------------- 1.6/2.7 GB 60.7 MB/s eta 0:00:19
     ----------------------- ---------------- 1.6/2.7 GB 59.4 MB/s eta 0:00:19
     ----------------------- ---------------- 1.6/2.7 GB 57.6 MB/s eta 0:00:20
     ----------------------- ---------------- 1.6/2.7 GB 55.7 MB/s eta 0:00:20
     ----------------------- ---------------- 1.6/2.7 GB 54.1 MB/s eta 0:00:21
     ------------------------ --------------- 1.6/2.7 GB 53.0 MB/s eta 0:00:21
     ------------------------ --------------- 1.6/2.7 GB 51.6 MB/s eta 0:00:21
     ------------------------ --------------- 1.6/2.7 GB 50.8 MB/s eta 0:00:21
     ------------------------ --------------- 1.7/2.7 GB 49.4 MB/s eta 0:00:22
     ------------------------ --------------- 1.7/2.7 GB 48.4 MB/s eta 0:00:22
     ------------------------ --------------- 1.7/2.7 GB 47.6 MB/s eta 0:00:22
     ------------------------ --------------- 1.7/2.7 GB 46.7 MB/s eta 0:00:23
     ------------------------ --------------- 1.7/2.7 GB 46.0 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 45.4 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 44.9 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 44.1 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 44.2 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 43.2 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 42.5 MB/s eta 0:00:23
     ------------------------- -------------- 1.7/2.7 GB 42.3 MB/s eta 0:00:23
     ------------------------- -------------- 1.8/2.7 GB 42.0 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 41.7 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 41.4 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 41.0 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 40.4 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 40.1 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 39.9 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 39.6 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 39.4 MB/s eta 0:00:23
     -------------------------- ------------- 1.8/2.7 GB 39.2 MB/s eta 0:00:23
     --------------------------- ------------ 1.8/2.7 GB 38.9 MB/s eta 0:00:23
     --------------------------- ------------ 1.8/2.7 GB 38.8 MB/s eta 0:00:23
     --------------------------- ------------ 1.8/2.7 GB 38.5 MB/s eta 0:00:23
     --------------------------- ------------ 1.9/2.7 GB 38.0 MB/s eta 0:00:23
     --------------------------- ------------ 1.9/2.7 GB 37.6 MB/s eta 0:00:23
     --------------------------- ------------ 1.9/2.7 GB 37.7 MB/s eta 0:00:23
     --------------------------- ------------ 1.9/2.7 GB 37.3 MB/s eta 0:00:23
     --------------------------- ------------ 1.9/2.7 GB 37.6 MB/s eta 0:00:22
     --------------------------- ------------ 1.9/2.7 GB 37.5 MB/s eta 0:00:22
     ---------------------------- ----------- 1.9/2.7 GB 37.7 MB/s eta 0:00:22
     ---------------------------- ----------- 1.9/2.7 GB 38.0 MB/s eta 0:00:21
     ---------------------------- ----------- 1.9/2.7 GB 38.5 MB/s eta 0:00:21
     ---------------------------- ----------- 1.9/2.7 GB 38.7 MB/s eta 0:00:21
     ---------------------------- ----------- 1.9/2.7 GB 38.9 MB/s eta 0:00:20
     ---------------------------- ----------- 1.9/2.7 GB 39.2 MB/s eta 0:00:20
     ---------------------------- ----------- 2.0/2.7 GB 39.5 MB/s eta 0:00:19
     ----------------------------- ---------- 2.0/2.7 GB 39.5 MB/s eta 0:00:19
     ----------------------------- ---------- 2.0/2.7 GB 39.2 MB/s eta 0:00:19
     ----------------------------- ---------- 2.0/2.7 GB 39.3 MB/s eta 0:00:19
     ----------------------------- ---------- 2.0/2.7 GB 39.8 MB/s eta 0:00:18
     ----------------------------- ---------- 2.0/2.7 GB 40.3 MB/s eta 0:00:18
     ----------------------------- ---------- 2.0/2.7 GB 40.4 MB/s eta 0:00:18
     ----------------------------- ---------- 2.0/2.7 GB 40.6 MB/s eta 0:00:17
     ------------------------------ --------- 2.0/2.7 GB 41.2 MB/s eta 0:00:17
     ------------------------------ --------- 2.0/2.7 GB 42.3 MB/s eta 0:00:16
     ------------------------------ --------- 2.1/2.7 GB 43.1 MB/s eta 0:00:15
     ------------------------------ --------- 2.1/2.7 GB 43.4 MB/s eta 0:00:15
     ------------------------------ --------- 2.1/2.7 GB 44.6 MB/s eta 0:00:14
     ------------------------------ --------- 2.1/2.7 GB 44.7 MB/s eta 0:00:14
     ------------------------------- -------- 2.1/2.7 GB 45.2 MB/s eta 0:00:14
     ------------------------------- -------- 2.1/2.7 GB 45.9 MB/s eta 0:00:13
     ------------------------------- -------- 2.1/2.7 GB 47.6 MB/s eta 0:00:13
     ------------------------------- -------- 2.1/2.7 GB 48.4 MB/s eta 0:00:12
     ------------------------------- -------- 2.1/2.7 GB 49.2 MB/s eta 0:00:12
     ------------------------------- -------- 2.2/2.7 GB 50.2 MB/s eta 0:00:11
     -------------------------------- ------- 2.2/2.7 GB 50.8 MB/s eta 0:00:11
     -------------------------------- ------- 2.2/2.7 GB 50.8 MB/s eta 0:00:11
     -------------------------------- ------- 2.2/2.7 GB 50.9 MB/s eta 0:00:11
     -------------------------------- ------- 2.2/2.7 GB 51.4 MB/s eta 0:00:10
     -------------------------------- ------- 2.2/2.7 GB 51.4 MB/s eta 0:00:10
     -------------------------------- ------- 2.2/2.7 GB 51.4 MB/s eta 0:00:10
     --------------------------------- ------ 2.2/2.7 GB 52.2 MB/s eta 0:00:09
     --------------------------------- ------ 2.2/2.7 GB 52.4 MB/s eta 0:00:09
     --------------------------------- ------ 2.3/2.7 GB 52.1 MB/s eta 0:00:09
     --------------------------------- ------ 2.3/2.7 GB 51.9 MB/s eta 0:00:09
     --------------------------------- ------ 2.3/2.7 GB 52.2 MB/s eta 0:00:09
     --------------------------------- ------ 2.3/2.7 GB 52.2 MB/s eta 0:00:08
     ---------------------------------- ----- 2.3/2.7 GB 52.1 MB/s eta 0:00:08
     ---------------------------------- ----- 2.3/2.7 GB 52.4 MB/s eta 0:00:08
     ---------------------------------- ----- 2.3/2.7 GB 52.2 MB/s eta 0:00:08
     ---------------------------------- ----- 2.3/2.7 GB 52.4 MB/s eta 0:00:08
     ---------------------------------- ----- 2.3/2.7 GB 52.4 MB/s eta 0:00:07
     ---------------------------------- ----- 2.4/2.7 GB 52.5 MB/s eta 0:00:07
     ----------------------------------- ---- 2.4/2.7 GB 53.0 MB/s eta 0:00:07
     ----------------------------------- ---- 2.4/2.7 GB 52.9 MB/s eta 0:00:07
     ----------------------------------- ---- 2.4/2.7 GB 52.7 MB/s eta 0:00:06
     ----------------------------------- ---- 2.4/2.7 GB 52.9 MB/s eta 0:00:06
     ----------------------------------- ---- 2.4/2.7 GB 53.0 MB/s eta 0:00:06
     ----------------------------------- ---- 2.4/2.7 GB 53.2 MB/s eta 0:00:06
     ------------------------------------ --- 2.4/2.7 GB 53.0 MB/s eta 0:00:06
     ------------------------------------ --- 2.4/2.7 GB 53.0 MB/s eta 0:00:05
     ------------------------------------ --- 2.5/2.7 GB 53.2 MB/s eta 0:00:05
     ------------------------------------ --- 2.5/2.7 GB 51.7 MB/s eta 0:00:05
     ------------------------------------ --- 2.5/2.7 GB 50.9 MB/s eta 0:00:05
     ------------------------------------ --- 2.5/2.7 GB 50.6 MB/s eta 0:00:05
     ------------------------------------ --- 2.5/2.7 GB 50.3 MB/s eta 0:00:05
     ------------------------------------ --- 2.5/2.7 GB 50.0 MB/s eta 0:00:05
     ------------------------------------- -- 2.5/2.7 GB 50.0 MB/s eta 0:00:04
     ------------------------------------- -- 2.5/2.7 GB 49.9 MB/s eta 0:00:04
     ------------------------------------- -- 2.5/2.7 GB 49.9 MB/s eta 0:00:04
     ------------------------------------- -- 2.5/2.7 GB 49.9 MB/s eta 0:00:04
     ------------------------------------- -- 2.5/2.7 GB 49.2 MB/s eta 0:00:04
     ------------------------------------- -- 2.6/2.7 GB 49.2 MB/s eta 0:00:04
     ------------------------------------- -- 2.6/2.7 GB 48.9 MB/s eta 0:00:03
     -------------------------------------- - 2.6/2.7 GB 48.6 MB/s eta 0:00:03
     -------------------------------------- - 2.6/2.7 GB 48.2 MB/s eta 0:00:03
     -------------------------------------- - 2.6/2.7 GB 48.0 MB/s eta 0:00:03
     -------------------------------------- - 2.6/2.7 GB 47.2 MB/s eta 0:00:03
     -------------------------------------- - 2.6/2.7 GB 46.7 MB/s eta 0:00:03
     -------------------------------------- - 2.6/2.7 GB 45.7 MB/s eta 0:00:02
     -------------------------------------- - 2.6/2.7 GB 45.4 MB/s eta 0:00:02
     -------------------------------------- - 2.6/2.7 GB 45.2 MB/s eta 0:00:02
     ---------------------------------------  2.6/2.7 GB 44.9 MB/s eta 0:00:02
     ---------------------------------------  2.7/2.7 GB 44.9 MB/s eta 0:00:02
     ---------------------------------------  2.7/2.7 GB 44.6 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.7 GB 44.0 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.7 GB 43.3 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.7 GB 42.6 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.7 GB 42.4 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.7 GB 42.4 MB/s eta 0:00:01
     ---------------------------------------  2.7/2.7 GB 41.8 MB/s eta 0:00:01
     ---------------------------------------- 2.7/2.7 GB 40.4 MB/s  0:00:47
Collecting torchaudio==2.2.2
  Downloading torchaudio-2.2.2%2Bcu118-cp312-cp312-win_amd64.whl (3.9 MB)
     ---------------------------------------- 0.0/3.9 MB ? eta -:--:--
     ---------------------------------------- 3.9/3.9 MB 26.3 MB/s  0:00:00
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (3.29.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (4.15.0)
Requirement already satisfied: sympy in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (1.14.0)
Requirement already satisfied: networkx in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (3.1.6)
Requirement already satisfied: fsspec in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2) (2026.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch==2.2.2) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy->torch==2.2.2) (1.3.0)
Installing collected packages: torch, torchaudio

   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device

Collecting huggingface_hub==0.25.0
  Downloading huggingface_hub-0.25.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (6.0.3)
Requirement already satisfied: requests in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (2.33.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (4.15.0)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface_hub==0.25.0) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (2026.4.22)
Downloading huggingface_hub-0.25.0-py3-none-any.whl (436 kB)
Installing collected packages: huggingface_hub
Successfully installed huggingface_hub-0.25.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
accelerate 1.13.0 requires torch>=2.0.0, which is not installed.
speechbrain 1.1.0 requires torch>=2.1.0, which is not installed.
speechbrain 1.1.0 requires torchaudio>=2.1.0, which is not installed.
transformers 5.7.0 requires huggingface-hub<2.0,>=1.5.0, but you have huggingface-hub 0.25.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Collecting pyannote.audio==3.1.1
  Downloading pyannote.audio-3.1.1-py2.py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: asteroid-filterbanks>=0.4 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.4.0)
Requirement already satisfied: einops>=0.6.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.25.0)
Requirement already satisfied: lightning>=2.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: omegaconf<3.0,>=2.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.3.0)
Requirement already satisfied: pyannote.core>=5.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.0.1)
Requirement already satisfied: pyannote.database>=5.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.1.1)
Requirement already satisfied: pyannote.metrics>=3.2 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pyannote.pipeline>=3.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pytorch-metric-learning>=2.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.9.0)
Requirement already satisfied: rich>=12.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (15.0.0)
Requirement already satisfied: semver>=3.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (3.0.4)
Requirement already satisfied: soundfile>=0.12.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.13.1)
Requirement already satisfied: speechbrain>=0.5.14 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.1.0)
Requirement already satisfied: tensorboardX>=2.6 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.5)
Collecting torch>=2.0.0 (from pyannote.audio==3.1.1)
  Downloading torch-2.11.0-cp312-cp312-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: torch-audiomentations>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.12.0)
Collecting torchaudio>=2.0.0 (from pyannote.audio==3.1.1)
  Downloading torchaudio-2.11.0-cp312-cp312-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: torchmetrics>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.9.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (6.0.3)
Requirement already satisfied: numpy in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (1.26.0)
Requirement already satisfied: typing-extensions in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (4.15.0)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (26.2)
Requirement already satisfied: requests in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2.33.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (4.67.3)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (0.15.3)
Requirement already satisfied: pytorch-lightning in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\LLM\ch03_venv\Lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13.5)
Requirement already satisfied: setuptools<82 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.1.6)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.23.0)
Requirement already satisfied: idna>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13)
Collecting numpy (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1)
  Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: pandas>=2.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (3.0.2)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2026.2)
Requirement already satisfied: scikit-learn>=1.6.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: scipy>=1.15.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.17.1)
Requirement already satisfied: optuna>=4.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.18.4)
Requirement already satisfied: colorlog in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (2.0.49)
Requirement already satisfied: Mako in c:\LLM\ch03_venv\Lib\site-packages (from alembic>=1.5.0->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.3.12)
Requirement already satisfied: six>=1.5 in c:\LLM\ch03_venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\LLM\ch03_venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->pyannote.audio==3.1.1) (0.1.2)
Requirement already satisfied: joblib>=1.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (3.6.0)
Requirement already satisfied: cffi>=1.0 in c:\LLM\ch03_venv\Lib\site-packages (from soundfile>=0.12.1->pyannote.audio==3.1.1) (2.0.0)
Requirement already satisfied: pycparser in c:\LLM\ch03_venv\Lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->pyannote.audio==3.1.1) (3.0)
Requirement already satisfied: hyperpyyaml>=0.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (1.2.3)
Requirement already satisfied: sentencepiece>=0.1.91 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.1)
Requirement already satisfied: ruamel.yaml<0.19.0,>=0.17.28 in c:\LLM\ch03_venv\Lib\site-packages (from hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.18.17)
Requirement already satisfied: ruamel.yaml.clib>=0.2.15 in c:\LLM\ch03_venv\Lib\site-packages (from ruamel.yaml<0.19.0,>=0.17.28->hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.15)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.4.22)
Requirement already satisfied: greenlet>=1 in c:\LLM\ch03_venv\Lib\site-packages (from sqlalchemy>=1.4.2->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->pyannote.audio==3.1.1) (1.3.0)
Requirement already satisfied: protobuf>=3.20 in c:\LLM\ch03_venv\Lib\site-packages (from tensorboardX>=2.6->pyannote.audio==3.1.1) (6.33.6)
Requirement already satisfied: julius<0.3,>=0.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (0.2.7)
Requirement already satisfied: torch-pitch-shift>=1.2.2 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.2.5)
Requirement already satisfied: primePy>=1.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-pitch-shift>=1.2.2->torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch>=2.0.0->pyannote.audio==3.1.1) (3.0.3)
Downloading pyannote.audio-3.1.1-py2.py3-none-any.whl (208 kB)
Downloading torch-2.11.0-cp312-cp312-win_amd64.whl (114.6 MB)
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
   -- ------------------------------------- 8.1/114.6 MB 41.8 MB/s eta 0:00:03
   ---------- ----------------------------- 29.4/114.6 MB 71.7 MB/s eta 0:00:02
   ---------------- ----------------------- 47.2/114.6 MB 75.1 MB/s eta 0:00:01
   ----------------------- ---------------- 66.1/114.6 MB 78.0 MB/s eta 0:00:01
   ----------------------------- ---------- 84.7/114.6 MB 80.6 MB/s eta 0:00:01
   ------------------------------------ -- 106.7/114.6 MB 84.1 MB/s eta 0:00:01
   --------------------------------------  114.3/114.6 MB 84.8 MB/s eta 0:00:01
   --------------------------------------  114.3/114.6 MB 84.8 MB/s eta 0:00:01
   --------------------------------------  114.3/114.6 MB 84.8 MB/s eta 0:00:01
   --------------------------------------  114.3/114.6 MB 84.8 MB/s eta 0:00:01
   --------------------------------------  114.3/114.6 MB 84.8 MB/s eta 0:00:01
   ---------------------------------------- 114.6/114.6 MB 47.2 MB/s  0:00:02
Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------  12.1/12.3 MB 54.1 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 42.9 MB/s  0:00:00
Downloading torchaudio-2.11.0-cp312-cp312-win_amd64.whl (328 kB)
Installing collected packages: torchaudio, numpy, torch, pyannote.audio

   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
   ---------------------------------------- 0/4 [torchaudio]
  Attempting uninstall: numpy
   ---------------------------------------- 0/4 [torchaudio]
    Found existing installation: numpy 1.26.0
   ---------------------------------------- 0/4 [torchaudio]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
    Uninstalling numpy-1.26.0:
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
      Successfully uninstalled numpy-1.26.0
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]
   ---------- ----------------------------- 1/4 [numpy]

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
  WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~%mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\LLM\ch03_venv\Lib\site-packages\~%mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 5.7.0 requires huggingface-hub<2.0,>=1.5.0, but you have huggingface-hub 0.25.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

In [3]:
# 1. 꼬인 패키지 삭제
%pip uninstall torch torchaudio pyannote.audio huggingface_hub -y

# 2. 이번에는 용량이 적은 'CPU 전용' 버전으로 설치 (용량 부족 시 훨씬 안전함)
# 이 명령어는 GPU 기능 없이 CPU로만 동작하도록 가벼운 버전을 설치합니다.
%pip install torch==2.2.2+cpu torchaudio==2.2.2+cpu --index-url https://download.pytorch.org/whl/cpu
%pip install huggingface_hub==0.25.0
%pip install pyannote.audio==3.1.1

Found existing installation: torch 2.11.0
Uninstalling torch-2.11.0:
  Successfully uninstalled torch-2.11.0
Found existing installation: torchaudio 2.11.0
Uninstalling torchaudio-2.11.0:
  Successfully uninstalled torchaudio-2.11.0
Found existing installation: pyannote.audio 3.1.1
Uninstalling pyannote.audio-3.1.1:
  Successfully uninstalled pyannote.audio-3.1.1
Found existing installation: huggingface-hub 0.25.0
Uninstalling huggingface-hub-0.25.0:
  Successfully uninstalled huggingface-hub-0.25.0
Note: you may need to restart the kernel to use updated packages.
Looking in indexes: https://download.pytorch.org/whl/cpu
Collecting torch==2.2.2+cpu
  Downloading torch-2.2.2%2Bcpu-cp312-cp312-win_amd64.whl (200.7 MB)
     ---------------------------------------- 0.0/200.7 MB ? eta -:--:--
     --- ---------------------------------- 16.3/200.7 MB 78.4 MB/s eta 0:00:03
     ------ ------------------------------- 33.3/200.7 MB 81.2 MB/s eta 0:00:03
     --------- ---------------------------- 49.8/200.7 MB 79.3 MB/s eta 0:00:02
     ------------ ------------------------- 65.8/200.7 MB 77.6 MB/s eta 0:00:02
     --------------- ---------------------- 83.1/200.7 MB 77.9 MB/s eta 0:00:02
     ------------------ ------------------ 101.7/200.7 MB 79.1 MB/s eta 0:00:02
     --------------------- --------------- 119.0/200.7 MB 79.2 MB/s eta 0:00:02
     ------------------------- ----------- 136.6/200.7 MB 80.0 MB/s eta 0:00:01
     ---------------------------- -------- 154.1/200.7 MB 80.1 MB/s eta 0:00:01
     ------------------------------- ----- 171.7/200.7 MB 80.1 MB/s eta 0:00:01
     ---------------------------------- -- 188.0/200.7 MB 79.5 MB/s eta 0:00:01
     ------------------------------------  200.5/200.7 MB 79.6 MB/s eta 0:00:01
     ------------------------------------  200.5/200.7 MB 79.6 MB/s eta 0:00:01
     ------------------------------------  200.5/200.7 MB 79.6 MB/s eta 0:00:01
     ---------------------------------------- 200.7/200.7 MB 67.5 MB/s  0:00:02
Collecting torchaudio==2.2.2+cpu
  Downloading torchaudio-2.2.2%2Bcpu-cp312-cp312-win_amd64.whl (2.3 MB)
     ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
     ---------------------------------------- 2.3/2.3 MB 44.1 MB/s  0:00:00
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (3.29.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (4.15.0)
Requirement already satisfied: sympy in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (1.14.0)
Requirement already satisfied: networkx in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (3.1.6)
Requirement already satisfied: fsspec in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (2026.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch==2.2.2+cpu) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy->torch==2.2.2+cpu) (1.3.0)
Installing collected packages: torch, torchaudio

   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
accelerate 1.13.0 requires huggingface_hub>=0.21.0, which is not installed.
speechbrain 1.1.0 requires huggingface_hub>=0.8.0, which is not installed.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Collecting huggingface_hub==0.25.0
  Downloading huggingface_hub-0.25.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (6.0.3)
Requirement already satisfied: requests in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (2.33.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface_hub==0.25.0) (4.15.0)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface_hub==0.25.0) (0.4.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface_hub==0.25.0) (2026.4.22)
Downloading huggingface_hub-0.25.0-py3-none-any.whl (436 kB)
Installing collected packages: huggingface_hub
Successfully installed huggingface_hub-0.25.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformers 5.7.0 requires huggingface-hub<2.0,>=1.5.0, but you have huggingface-hub 0.25.0 which is incompatible.
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Collecting pyannote.audio==3.1.1
  Downloading pyannote.audio-3.1.1-py2.py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: asteroid-filterbanks>=0.4 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.4.0)
Requirement already satisfied: einops>=0.6.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.25.0)
Requirement already satisfied: lightning>=2.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: omegaconf<3.0,>=2.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.3.0)
Requirement already satisfied: pyannote.core>=5.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.0.1)
Requirement already satisfied: pyannote.database>=5.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.1.1)
Requirement already satisfied: pyannote.metrics>=3.2 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pyannote.pipeline>=3.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pytorch-metric-learning>=2.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.9.0)
Requirement already satisfied: rich>=12.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (15.0.0)
Requirement already satisfied: semver>=3.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (3.0.4)
Requirement already satisfied: soundfile>=0.12.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.13.1)
Requirement already satisfied: speechbrain>=0.5.14 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.1.0)
Requirement already satisfied: tensorboardX>=2.6 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.5)
Requirement already satisfied: torch>=2.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.2.2+cpu)
Requirement already satisfied: torch-audiomentations>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.12.0)
Requirement already satisfied: torchaudio>=2.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.2.2+cpu)
Requirement already satisfied: torchmetrics>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.9.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (6.0.3)
Requirement already satisfied: numpy in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (2.4.4)
Requirement already satisfied: typing-extensions in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (4.15.0)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (26.2)
Requirement already satisfied: requests in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2.33.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (4.67.3)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (0.15.3)
Requirement already satisfied: pytorch-lightning in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\LLM\ch03_venv\Lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13.5)
Requirement already satisfied: sympy in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (1.14.0)
Requirement already satisfied: networkx in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.1.6)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.23.0)
Requirement already satisfied: idna>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13)
Requirement already satisfied: pandas>=2.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (3.0.2)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2026.2)
Requirement already satisfied: scikit-learn>=1.6.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: scipy>=1.15.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.17.1)
Requirement already satisfied: optuna>=4.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.18.4)
Requirement already satisfied: colorlog in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (2.0.49)
Requirement already satisfied: Mako in c:\LLM\ch03_venv\Lib\site-packages (from alembic>=1.5.0->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.3.12)
Requirement already satisfied: six>=1.5 in c:\LLM\ch03_venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\LLM\ch03_venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->pyannote.audio==3.1.1) (0.1.2)
Requirement already satisfied: joblib>=1.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (3.6.0)
Requirement already satisfied: cffi>=1.0 in c:\LLM\ch03_venv\Lib\site-packages (from soundfile>=0.12.1->pyannote.audio==3.1.1) (2.0.0)
Requirement already satisfied: pycparser in c:\LLM\ch03_venv\Lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->pyannote.audio==3.1.1) (3.0)
Requirement already satisfied: hyperpyyaml>=0.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (1.2.3)
Requirement already satisfied: sentencepiece>=0.1.91 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.1)
Requirement already satisfied: ruamel.yaml<0.19.0,>=0.17.28 in c:\LLM\ch03_venv\Lib\site-packages (from hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.18.17)
Requirement already satisfied: ruamel.yaml.clib>=0.2.15 in c:\LLM\ch03_venv\Lib\site-packages (from ruamel.yaml<0.19.0,>=0.17.28->hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.15)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.4.22)
Requirement already satisfied: greenlet>=1 in c:\LLM\ch03_venv\Lib\site-packages (from sqlalchemy>=1.4.2->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (3.5.0)
Requirement already satisfied: protobuf>=3.20 in c:\LLM\ch03_venv\Lib\site-packages (from tensorboardX>=2.6->pyannote.audio==3.1.1) (6.33.6)
Requirement already satisfied: julius<0.3,>=0.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (0.2.7)
Requirement already satisfied: torch-pitch-shift>=1.2.2 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.2.5)
Requirement already satisfied: primePy>=1.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-pitch-shift>=1.2.2->torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch>=2.0.0->pyannote.audio==3.1.1) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy->torch>=2.0.0->pyannote.audio==3.1.1) (1.3.0)
Downloading pyannote.audio-3.1.1-py2.py3-none-any.whl (208 kB)
Installing collected packages: pyannote.audio
Successfully installed pyannote.audio-3.1.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

In [1]:
# 1. 라이브러리 임포트 및 호환성 패치
import torchaudio
import torch
from pyannote.audio import Pipeline

# torchaudio 백엔드 에러 방지용 패치
if not hasattr(torchaudio, 'set_audio_backend'):
    torchaudio.set_audio_backend = lambda x: None

# 2. 모델 불러오기 (huggingface_hub 0.25.0 버전에 맞게 'token' 사용)
print("⏳ 모델 로딩 중... (약 1~2분 소요될 수 있습니다)")
pipeline = Pipeline.from_pretrained(
    "pyannote/speaker-diarization-3.1",
    token="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"
)

# 3. 장치 설정 (CPU 모드)
pipeline.to(torch.device("cpu"))
print("✅ 준비 완료! 화자 분리 분석을 시작합니다.")

# 4. 분석 실행 (audio 폴더 내 파일 경로 확인 필수!)
# 58초 분량이라 CPU 환경에서도 금방 끝날 거예요.
diarization = pipeline("audio/lsy_audio_2023_58s.mp3")

# 5. 결과 저장 (RTTM 형식)
with open("audio/result.rttm", "w", encoding='utf-8') as rttm:
    diarization.write_rttm(rttm)

print("✨ [성공] 화자 분리가 완료되었습니다!")
print("📁 결과 파일 위치: audio/result.rttm")

OSError: [WinError 126] 지정된 모듈을 찾을 수 없습니다. Error loading "c:\LLM\ch03_venv\Lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.

In [2]:
# 1. 기존에 꼬여있는 모든 torch 관련 패키지 강제 삭제
%pip uninstall torch torchaudio pyannote.audio -y

# 2. CPU 전용 버전으로 '깨끗하게' 재설치 (인덱스를 정확히 지정합니다)
# --no-cache-dir 옵션을 넣어 용량 부족으로 인해 깨진 파일이 재사용되지 않게 합니다.
%pip install --no-cache-dir torch==2.2.2+cpu torchaudio==2.2.2+cpu --index-url https://download.pytorch.org/whl/cpu

# 3. pyannote.audio 재설치
%pip install pyannote.audio==3.1.1

Found existing installation: torch 2.2.2+cpu
Uninstalling torch-2.2.2+cpu:
  Successfully uninstalled torch-2.2.2+cpu
Found existing installation: torchaudio 2.2.2+cpu
Uninstalling torchaudio-2.2.2+cpu:
  Successfully uninstalled torchaudio-2.2.2+cpu
Found existing installation: pyannote.audio 3.1.1
Uninstalling pyannote.audio-3.1.1:
  Successfully uninstalled pyannote.audio-3.1.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Failed to remove contents in a temporary directory 'C:\Users\lsh8389\AppData\Local\Temp\pip-uninstall-0wha_u8g'.
You can safely remove it manually.

Looking in indexes: https://download.pytorch.org/whl/cpu
Collecting torch==2.2.2+cpu
  Downloading torch-2.2.2%2Bcpu-cp312-cp312-win_amd64.whl (200.7 MB)
     ---------------------------------------- 0.0/200.7 MB ? eta -:--:--
     --- ---------------------------------- 20.2/200.7 MB 98.1 MB/s eta 0:00:02
     -------- ---------------------------- 44.0/200.7 MB 103.7 MB/s eta 0:00:02
     ----------- ------------------------- 65.0/200.7 MB 103.6 MB/s eta 0:00:02
     --------------- --------------------- 86.2/200.7 MB 103.8 MB/s eta 0:00:02
     ------------------- ---------------- 109.1/200.7 MB 105.5 MB/s eta 0:00:01
     ----------------------- ------------ 130.3/200.7 MB 105.4 MB/s eta 0:00:01
     --------------------------- -------- 155.5/200.7 MB 106.8 MB/s eta 0:00:01
     ------------------------------- ---- 174.9/200.7 MB 105.4 MB/s eta 0:00:01
     -----------------------------------  198.7/200.7 MB 105.8 MB/s eta 0:00:01
     --------------------------------------- 200.7/200.7 MB 106.9 MB/s  0:00:01
Collecting torchaudio==2.2.2+cpu
  Downloading torchaudio-2.2.2%2Bcpu-cp312-cp312-win_amd64.whl (2.3 MB)
     ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
     ---------------------------------------- 2.3/2.3 MB 129.5 MB/s  0:00:00
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (3.29.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (4.15.0)
Requirement already satisfied: sympy in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (1.14.0)
Requirement already satisfied: networkx in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (3.1.6)
Requirement already satisfied: fsspec in c:\LLM\ch03_venv\Lib\site-packages (from torch==2.2.2+cpu) (2026.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch==2.2.2+cpu) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy->torch==2.2.2+cpu) (1.3.0)
Installing collected packages: torch, torchaudio

   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   ---------------------------------------- 0/2 [torch]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   -------------------- ------------------- 1/2 [torchaudio]
   ---------------------------------------- 2/2 [torchaudio]

Successfully installed torch-2.2.2+cpu torchaudio-2.2.2+cpu
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

Collecting pyannote.audio==3.1.1
  Using cached pyannote.audio-3.1.1-py2.py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: asteroid-filterbanks>=0.4 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.4.0)
Requirement already satisfied: einops>=0.6.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.8.2)
Requirement already satisfied: huggingface-hub>=0.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.25.0)
Requirement already satisfied: lightning>=2.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: omegaconf<3.0,>=2.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.3.0)
Requirement already satisfied: pyannote.core>=5.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.0.1)
Requirement already satisfied: pyannote.database>=5.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (6.1.1)
Requirement already satisfied: pyannote.metrics>=3.2 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pyannote.pipeline>=3.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pytorch-metric-learning>=2.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.9.0)
Requirement already satisfied: rich>=12.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (15.0.0)
Requirement already satisfied: semver>=3.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (3.0.4)
Requirement already satisfied: soundfile>=0.12.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.13.1)
Requirement already satisfied: speechbrain>=0.5.14 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.1.0)
Requirement already satisfied: tensorboardX>=2.6 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.6.5)
Requirement already satisfied: torch>=2.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.2.2+cpu)
Requirement already satisfied: torch-audiomentations>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (0.12.0)
Requirement already satisfied: torchaudio>=2.0.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (2.2.2+cpu)
Requirement already satisfied: torchmetrics>=0.11.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.audio==3.1.1) (1.9.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (4.9.3)
Requirement already satisfied: PyYAML>=5.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from omegaconf<3.0,>=2.1->pyannote.audio==3.1.1) (6.0.3)
Requirement already satisfied: numpy in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (2.4.4)
Requirement already satisfied: typing-extensions in c:\LLM\ch03_venv\Lib\site-packages (from asteroid-filterbanks>=0.4->pyannote.audio==3.1.1) (4.15.0)
Requirement already satisfied: filelock in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.2.0)
Requirement already satisfied: packaging>=20.9 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (26.2)
Requirement already satisfied: requests in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2.33.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\LLM\ch03_venv\Lib\site-packages (from huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (4.67.3)
Requirement already satisfied: lightning-utilities<2.0,>=0.10.0 in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (0.15.3)
Requirement already satisfied: pytorch-lightning in c:\LLM\ch03_venv\Lib\site-packages (from lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\LLM\ch03_venv\Lib\site-packages (from fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13.5)
Requirement already satisfied: sympy in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (1.14.0)
Requirement already satisfied: networkx in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.6.1)
Requirement already satisfied: jinja2 in c:\LLM\ch03_venv\Lib\site-packages (from torch>=2.0.0->pyannote.audio==3.1.1) (3.1.6)
Requirement already satisfied: colorama in c:\LLM\ch03_venv\Lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (0.4.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\LLM\ch03_venv\Lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (1.23.0)
Requirement already satisfied: idna>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<2028.0,>=2022.5.0->lightning>=2.0.1->pyannote.audio==3.1.1) (3.13)
Requirement already satisfied: pandas>=2.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (3.0.2)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\LLM\ch03_venv\Lib\site-packages (from pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (2026.2)
Requirement already satisfied: scikit-learn>=1.6.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.8.0)
Requirement already satisfied: scipy>=1.15.1 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.17.1)
Requirement already satisfied: optuna>=4.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (4.8.0)
Requirement already satisfied: alembic>=1.5.0 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.18.4)
Requirement already satisfied: colorlog in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\LLM\ch03_venv\Lib\site-packages (from optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (2.0.49)
Requirement already satisfied: Mako in c:\LLM\ch03_venv\Lib\site-packages (from alembic>=1.5.0->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (1.3.12)
Requirement already satisfied: six>=1.5 in c:\LLM\ch03_venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.3->pyannote.core>=5.0.0->pyannote.audio==3.1.1) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\LLM\ch03_venv\Lib\site-packages (from rich>=12.0.0->pyannote.audio==3.1.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\LLM\ch03_venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->pyannote.audio==3.1.1) (0.1.2)
Requirement already satisfied: joblib>=1.3.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\LLM\ch03_venv\Lib\site-packages (from scikit-learn>=1.6.1->pyannote.metrics>=3.2->pyannote.audio==3.1.1) (3.6.0)
Requirement already satisfied: cffi>=1.0 in c:\LLM\ch03_venv\Lib\site-packages (from soundfile>=0.12.1->pyannote.audio==3.1.1) (2.0.0)
Requirement already satisfied: pycparser in c:\LLM\ch03_venv\Lib\site-packages (from cffi>=1.0->soundfile>=0.12.1->pyannote.audio==3.1.1) (3.0)
Requirement already satisfied: hyperpyyaml>=0.0.1 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (1.2.3)
Requirement already satisfied: sentencepiece>=0.1.91 in c:\LLM\ch03_venv\Lib\site-packages (from speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.1)
Requirement already satisfied: ruamel.yaml<0.19.0,>=0.17.28 in c:\LLM\ch03_venv\Lib\site-packages (from hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.18.17)
Requirement already satisfied: ruamel.yaml.clib>=0.2.15 in c:\LLM\ch03_venv\Lib\site-packages (from ruamel.yaml<0.19.0,>=0.17.28->hyperpyyaml>=0.0.1->speechbrain>=0.5.14->pyannote.audio==3.1.1) (0.2.15)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\LLM\ch03_venv\Lib\site-packages (from requests->huggingface-hub>=0.13.0->pyannote.audio==3.1.1) (2026.4.22)
Requirement already satisfied: greenlet>=1 in c:\LLM\ch03_venv\Lib\site-packages (from sqlalchemy>=1.4.2->optuna>=4.2.0->pyannote.pipeline>=3.0.1->pyannote.audio==3.1.1) (3.5.0)
Requirement already satisfied: protobuf>=3.20 in c:\LLM\ch03_venv\Lib\site-packages (from tensorboardX>=2.6->pyannote.audio==3.1.1) (6.33.6)
Requirement already satisfied: julius<0.3,>=0.2.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (0.2.7)
Requirement already satisfied: torch-pitch-shift>=1.2.2 in c:\LLM\ch03_venv\Lib\site-packages (from torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.2.5)
Requirement already satisfied: primePy>=1.3 in c:\LLM\ch03_venv\Lib\site-packages (from torch-pitch-shift>=1.2.2->torch-audiomentations>=0.11.0->pyannote.audio==3.1.1) (1.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\LLM\ch03_venv\Lib\site-packages (from jinja2->torch>=2.0.0->pyannote.audio==3.1.1) (3.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\LLM\ch03_venv\Lib\site-packages (from sympy->torch>=2.0.0->pyannote.audio==3.1.1) (1.3.0)
Using cached pyannote.audio-3.1.1-py2.py3-none-any.whl (208 kB)
Installing collected packages: pyannote.audio
Successfully installed pyannote.audio-3.1.1
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~orch (c:\LLM\ch03_venv\Lib\site-packages)

In [1]:
import numpy as np
import pyannote.audio
print(f"✅ 넘파이 버전: {np.__version__}")
print(f"✅ Pyannote 버전: {pyannote.audio.__version__}")

# 여기서 에러가 안 난다면, 아까 드린 '진행 바 코드'를 그대로 실행하시면 됩니다!

c:\LLM\ch05_venv\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
c:\LLM\ch05_venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

✅ 넘파이 버전: 1.26.4
✅ Pyannote 버전: 3.1.1

In [1]:
import torch
import torchaudio
from pyannote.audio import Pipeline
from pyannote.audio.pipelines.utils.hook import ProgressHook

# 1. 윈도우 환경 패치 (경고 무시)
import warnings
warnings.filterwarnings("ignore")

if not hasattr(torchaudio, 'set_audio_backend'):
    torchaudio.set_audio_backend = lambda x: None

# 2. 모델 로드 (token -> use_auth_token 으로 변경)
print("⏳ 모델을 불러오는 중입니다... (약 1~2분 소요)")
try:
    pipeline = Pipeline.from_pretrained(
        "pyannote/speaker-diarization-3.1",
        use_auth_token="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" # 여기를 수정했습니다!
    )
    pipeline.to(torch.device("cpu"))
    print("✅ 모델 로드 성공!")

    # 3. 분석 시작
    print("🚀 화자 분리 분석 시작... (하단 진행바 확인)")
    with ProgressHook() as hook:
        diarization = pipeline("audio/lsy_audio_2023_58s.mp3", hook=hook)

    # 4. 결과 저장
    with open("audio/result.rttm", "w", encoding='utf-8') as rttm:
        diarization.write_rttm(rttm)

    print("\n✨ 모든 분석 완료! audio/result.rttm 파일을 확인하세요.")

except Exception as e:
    print(f"\n❌ 다시 에러 발생: {e}")

c:\LLM\ch05_venv\Lib\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
c:\LLM\ch05_venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\LLM\ch05_venv\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:43: UserWarning: torchaudio._backend.get_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  backend = torchaudio.get_audio_backend()
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
c:\LLM\ch05_venv\Lib\site-packages\speechbrain\utils\torch_audio_backend.py:22: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
torchvision is not available - cannot save figures
The torchaudio backend is switched to 'soundfile'. Note that 'sox_io' is not supported on Windows.
c:\LLM\ch05_venv\Lib\site-packages\pyannote\audio\pipelines\speaker_verification.py:53: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend(backend)
c:\LLM\ch05_venv\Lib\site-packages\pyannote\audio\tasks\segmentation\mixins.py:37: UserWarning: `torchaudio.backend.common.AudioMetaData` has been moved to `torchaudio.AudioMetaData`. Please update the import path.
  from torchaudio.backend.common import AudioMetaData

⏳ 모델을 불러오는 중입니다... (약 1~2분 소요)
✅ 모델 로드 성공!
🚀 화자 분리 분석 시작... (하단 진행바 확인)

✨ 모든 분석 완료! audio/result.rttm 파일을 확인하세요.

In [2]:
import pandas as pd

# 1. RTTM 파일 경로 설정
rttm_path = "audio/result.rttm"

# 2. RTTM 파일 읽기 (공백으로 구분됨)
# RTTM 형식: SPEAKER 파일명 1 시작시간 지속시간 <NA> <NA> 화자ID <NA> <NA>
column_names = [
    "type", "file_id", "chnl", "start", "duration", 
    "ortho", "look", "speaker_id", "conf", "feat"
]

try:
    # 파일을 읽어오고 필요한 컬럼만 추출합니다.
    df = pd.read_csv(rttm_path, sep=r'\s+', names=column_names, engine='python')
    
    # 종료 시간(end) 계산: 시작 시간 + 지속 시간
    df["end"] = df["start"] + df["duration"]
    
    # 실습에 필요한 컬럼만 선택 (start, end, speaker_id)
    df_rttm = df[["start", "end", "speaker_id"]].copy()
    
    # 나중에 Whisper로 텍스트를 채울 'text' 컬럼도 미리 만들어둡니다.
    df_rttm["text"] = ""
    
    print("✅ RTTM 파일을 성공적으로 데이터프레임으로 변환했습니다!")
    display(df_rttm.head())
    
    # (선택) 나중을 위해 CSV로도 저장해둡니다.
    # df_rttm.to_csv("audio/result.csv", index=False, sep='|')

except FileNotFoundError:
    print("❌ result.rttm 파일을 찾을 수 없습니다. 경로를 확인해주세요.")

✅ RTTM 파일을 성공적으로 데이터프레임으로 변환했습니다!

    start     end  speaker_id text
0   0.212   0.908  SPEAKER_00
1   1.367   6.409  SPEAKER_00
2   6.986  10.534  SPEAKER_00
3  11.010  16.766  SPEAKER_00
4  17.190  21.553  SPEAKER_00

In [3]:
# 3. SPEAKER_00과 SPEAKER_01로 표시된 부분에 실제 이름을 넣습니다.
name_dict = {
    "SPEAKER_00": "이성용",  # 성용님 성함이나 원하는 이름을 넣으세요
    "SPEAKER_01": "AI 비서"
}

# 'name' 컬럼을 새로 만들어서 이름을 채워줍니다.
df_rttm["name"] = df_rttm["speaker_id"].apply(lambda x: name_dict.get(x, "알 수 없음"))

# 결과 확인
display(df_rttm.head())

    start     end  speaker_id text name
0   0.212   0.908  SPEAKER_00       이성용
1   1.367   6.409  SPEAKER_00       이성용
2   6.986  10.534  SPEAKER_00       이성용
3  11.010  16.766  SPEAKER_00       이성용
4  17.190  21.553  SPEAKER_00       이성용

In [2]:
import whisper
import pandas as pd

# 1. Whisper 모델 로드 (가장 가벼운 'tiny' 또는 중간급 'base' 추천)
print("⏳ Whisper 모델을 로딩 중입니다...")
model = whisper.load_model("base") 

# 2. 오디오 파일에서 텍스트 추출
print("🚀 텍스트 추출(STT) 시작... 오디오 길이에 따라 몇 분 소요될 수 있습니다.")
result = model.transcribe("audio/lsy_audio_2023_58s.mp3")

# 3. 추출된 문장들을 데이터프레임 형식으로 정리
segments = result['segments']
texts_with_time = []

for seg in segments:
    texts_with_time.append({
        "start": seg['start'],
        "end": seg['end'],
        "text": seg['text'].strip()
    })

df_whisper = pd.DataFrame(texts_with_time)
print("✅ 텍스트 추출 완료!")
display(df_whisper.head())

⏳ Whisper 모델을 로딩 중입니다...
🚀 텍스트 추출(STT) 시작... 오디오 길이에 따라 몇 분 소요될 수 있습니다.

c:\LLM\ch05_venv\Lib\site-packages\whisper\transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

✅ 텍스트 추출 완료!

   start    end                                        text
0   0.00   6.96  안녕하세요. 강의는 gpt api로 첫번 만들기라는 내용을 다루는 강입니다.
1   6.96  11.76                 gpt api에 대해서 생소하신 분들도 있을 텐데
2  11.76  17.44                 우리가 잘 알고 있는 채 gpt를 기능을 이용해서
3  17.44  22.04       우리가 원하는 프로그램을 어떻게 만드는지에 대해서 이야기할 거예요.
4  22.04  24.80                     그래서 이런 강의들이 사실 많이 있습니다.

In [1]:
import pandas as pd

# RTTM 파일 경로 (본인의 경로에 맞게 수정)
rttm_path = "audio/result.rttm"

column_names = [
    "type", "file_id", "chnl", "start", "duration", 
    "ortho", "look", "speaker_id", "conf", "feat"
]

try:
    # 1. 파일 읽기
    df_temp = pd.read_csv(rttm_path, sep=r'\s+', names=column_names, engine='python')
    
    # 2. 필요한 컬럼만 추출하여 df_rttm 생성
    df_rttm = df_temp[["start", "duration", "speaker_id"]].copy()
    df_rttm["end"] = df_rttm["start"] + df_rttm["duration"]
    df_rttm["text"] = "" # 텍스트를 담을 빈칸 생성
    
    # 3. 화자 이름 넣기 (이름은 원하시는 대로 수정하세요)
    name_dict = {
        "SPEAKER_00": "이성용",
        "SPEAKER_01": "강사님"
    }
    df_rttm["name"] = df_rttm["speaker_id"].apply(lambda x: name_dict.get(x, "알 수 없음"))
    
    print("✅ df_rttm 변수가 성공적으로 생성되었습니다!")
    display(df_rttm.head())

except Exception as e:
    print(f"❌ 에러 발생: {e}")

✅ df_rttm 변수가 성공적으로 생성되었습니다!

    start  duration  speaker_id     end text name
0   0.212     0.696  SPEAKER_00   0.908       이성용
1   1.367     5.042  SPEAKER_00   6.409       이성용
2   6.986     3.548  SPEAKER_00  10.534       이성용
3  11.010     5.756  SPEAKER_00  16.766       이성용
4  17.190     4.363  SPEAKER_00  21.553       이성용

In [3]:
import pandas as pd
import whisper

# 1. RTTM 로드 및 df_rttm 생성
rttm_path = "audio/result.rttm"
column_names = ["type", "file_id", "chnl", "start", "duration", "ortho", "look", "speaker_id", "conf", "feat"]
df_temp = pd.read_csv(rttm_path, sep=r'\s+', names=column_names, engine='python')
df_rttm = df_temp[["start", "duration", "speaker_id"]].copy()
df_rttm["end"] = df_rttm["start"] + df_rttm["duration"]
df_rttm["text"] = ""

# 2. 화자 이름 설정
name_dict = {"SPEAKER_00": "이성용", "SPEAKER_01": "강사님"}
df_rttm["name"] = df_rttm["speaker_id"].apply(lambda x: name_dict.get(x, "알 수 없음"))

# 3. Whisper 추출 (이미 실행했다면 다시 로드하지 않아도 되지만, 에러 방지를 위해 변수만 확인)
# 만약 df_whisper가 정말 없다면 아래 문장을 주석 해제하고 실행하세요.
# model = whisper.load_model("base")
# result = model.transcribe("audio/lsy_audio_2023_58s.mp3")
# df_whisper = pd.DataFrame(result['segments'])[['start', 'end', 'text']]

print("✅ df_rttm과 df_whisper 준비 완료!")

✅ df_rttm과 df_whisper 준비 완료!

In [5]:
import pandas as pd

# 1. df_whisper를 확실하게 다시 정의합니다.
# (아까 result = model.transcribe(...)가 성공했으므로 result 변수는 살아있을 겁니다)
try:
    df_whisper = pd.DataFrame(result['segments'])[['start', 'end', 'text']]
    print("✅ df_whisper 변수를 다시 생성했습니다.")
except NameError:
    print("❌ result 변수도 사라진 것 같습니다. Whisper 추출 셀부터 다시 실행해야 합니다.")

# 2. 화자 정보(df_rttm)와 결합 시도
try:
    for i, rttm_row in df_rttm.iterrows():
        matched_text = df_whisper[
            (df_whisper['start'] >= rttm_row['start'] - 0.5) & 
            (df_whisper['start'] <= rttm_row['end'] + 0.5)
        ]['text'].values
        
        df_rttm.at[i, 'text'] = " ".join(matched_text).strip()
    
    print("✨ 화자 정보와 텍스트 결합 성공!")
    display(df_rttm.head())
except NameError:
    print("❌ df_rttm 변수가 없습니다. RTTM 로드 셀을 다시 실행해 주세요.")

❌ result 변수도 사라진 것 같습니다. Whisper 추출 셀부터 다시 실행해야 합니다.
❌ df_rttm 변수가 없습니다. RTTM 로드 셀을 다시 실행해 주세요.

In [6]:
import pandas as pd
import whisper

# 1. RTTM 로드 및 df_rttm 생성
rttm_path = "audio/result.rttm"
column_names = ["type", "file_id", "chnl", "start", "duration", "ortho", "look", "speaker_id", "conf", "feat"]

try:
    # RTTM 읽기
    df_temp = pd.read_csv(rttm_path, sep=r'\s+', names=column_names, engine='python')
    df_rttm = df_temp[["start", "duration", "speaker_id"]].copy()
    df_rttm["end"] = df_rttm["start"] + df_rttm["duration"]
    
    # 이름 설정
    name_dict = {"SPEAKER_00": "이성용", "SPEAKER_01": "강사님"}
    df_rttm["name"] = df_rttm["speaker_id"].apply(lambda x: name_dict.get(x, "알 수 없음"))
    
    # 2. Whisper 다시 실행 (변수가 사라졌으므로 모델 로드부터 다시 합니다)
    print("⏳ Whisper 모델 로딩 및 STT 추출 중... (잠시만 기다려주세요)")
    model = whisper.load_model("base")
    result = model.transcribe("audio/lsy_audio_2023_58s.mp3")
    df_whisper = pd.DataFrame(result['segments'])[['start', 'end', 'text']]
    
    # 3. 화자 정보와 텍스트 결합
    for i, rttm_row in df_rttm.iterrows():
        matched_text = df_whisper[
            (df_whisper['start'] >= rttm_row['start'] - 0.5) & 
            (df_whisper['start'] <= rttm_row['end'] + 0.5)
        ]['text'].values
        df_rttm.at[i, 'text'] = " ".join(matched_text).strip()
    
    print("✨ 모든 데이터 복구 및 결합 완료!")
    display(df_rttm.head())

except FileNotFoundError:
    print("❌ 파일 경로를 확인해주세요. audio 폴더 안에 파일이 없나봐요!")
except Exception as e:
    print(f"❌ 에러 발생: {e}")

⏳ Whisper 모델 로딩 및 STT 추출 중... (잠시만 기다려주세요)

c:\LLM\ch05_venv\Lib\site-packages\whisper\transcribe.py:132: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")

✨ 모든 데이터 복구 및 결합 완료!

,start,duration,speaker_id,end,name,text
0,0.212,0.696,SPEAKER_00,0.908,이성용,안녕하세요. 강의는 gpt api로 첫번 만들기라는 내용을 다루는 강입니다.
1,1.367,5.042,SPEAKER_00,6.409,이성용,
2,6.986,3.548,SPEAKER_00,10.534,이성용,gpt api에 대해서 생소하신 분들도 있을 텐데
3,11.010,5.756,SPEAKER_00,16.766,이성용,우리가 잘 알고 있는 채 gpt를 기능을 이용해서
4,17.190,4.363,SPEAKER_00,21.553,이성용,우리가 원하는 프로그램을 어떻게 만드는지에 대해서 이야기할 거예요. 그래서 이런 ...

In [7]:
import os
from dotenv import load_dotenv
from openai import OpenAI

# 1. .env 파일에 저장된 API 키 로드
load_dotenv()
api_key = os.getenv("OPENAI_API_KEY")

# 2. OpenAI 클라이언트 생성
client = OpenAI(api_key=api_key)

print("✅ OpenAI 클라이언트 준비 완료!")

✅ OpenAI 클라이언트 준비 완료!

In [9]:
import json

# 이름과 내용만 추출하여 리스트로 만듭니다.
meeting_content = df_rttm[['name', 'text']].to_dict(orient='records')

# 확인용 출력 (선택 사항)
# print(json.dumps(meeting_content, indent=2, ensure_ascii=False))

In [11]:
print("⏳ GPT가 회의록을 요약하고 있습니다...")

response = client.chat.completions.create(
    model="gpt-4o-mini", # 가성비 좋은 모델입니다.
    messages=[
        {
            "role": "system", 
            "content": "너는 전문 비서야. 제공된 대화 내용을 바탕으로 '주요 안건', '결정 사항', '향후 계획'을 포함한 깔끔한 회의록을 마크다운 형식으로 작성해줘."
        },
        {
            "role": "user", 
            "content": f"다음 내용을 요약해줘: {json.dumps(meeting_content, ensure_ascii=False)}"
        }
    ]
)

# 최종 결과 출력
print("\n✨ [AI 회의 요약 결과] ✨")
print(response.choices[0].message.content)

⏳ GPT가 회의록을 요약하고 있습니다...

✨ [AI 회의 요약 결과] ✨
# 회의록

## 주요 안건
- 강의 주제: "GPT API로 첫번 만들기"
- 강의 내용 개요: GPT API의 기능을 이용하여 원하는 프로그램을 만드는 방법 설명

## 결정 사항
- 강의의 주요 초점은 GPT API를 통해 미션을 수행하는 프로그램을 만드는 과정에 있음을 강조함
- 강의에서 다룰 예제: 음악 플레이리스트 동영상을 자동으로 생성하는 프로그램

## 향후 계획
- 강의 진행 시 실제 프로그램 실행 모습을 시연할 계획
- 참가자들이 GPT API에 대한 이해도를 높일 수 있도록 다양한 설명과 예제를 제공할 예정

In [12]:
from docx import Document

# 1. 워드 문서 객체 생성
doc = Document()

# 2. 문서 제목 추가
doc.add_heading('AI 회의록 요약 결과', 0)

# 3. GPT가 생성한 요약 내용 가져오기 (위에서 출력된 response 내용)
summary_text = response.choices[0].message.content

# 4. 내용 추가
doc.add_paragraph(summary_text)

# 5. 파일 저장 (ch05 폴더 안에 생성됩니다)
output_path = "meeting_summary.docx"
doc.save(output_path)

print(f"🎉 모든 실습 완료! '{output_path}' 파일이 생성되었습니다.")

🎉 모든 실습 완료! 'meeting_summary.docx' 파일이 생성되었습니다.

In [4]:
# 현재 메모리에 있는 변수 목록 확인
%who

df_whisper	 model	 pd	 result	 seg	 segments	 texts_with_time	 whisper